### ISSUE TITLE
Saved (and Crit?) button for Damage and Healing

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#103]
Related to #102 

Make it easier to type in a value and have it automatically half rounding down (or double ? not quite valid for damage which only doubles the roll and not the plus, but if the numbers are rolled in-game with the updated character sheet in #92 then this could enable it).

Note: have some friends who have dyscalculia and it would make it easier for them to run games!

**Comment by Splinter714** [comment]
To clarify, is this separate from the current /2 and x2 buttons on the damage/healing calculator?

**Comment by Rycochet** [comment]
I honestly can't remember any more - maybe check the changelog for when those were added and if this is more recent then it would be something else.

Got a feeling that it might have been before they got added as they certainly do the job (even if I never use them lol)

**Comment by Splinter714** [comment]
I can't find when those buttons were added, but it seems the functionality is there. Perhaps with new character sheet, this should be revisited and perhaps damage automatically doubled/halved, but going to close this one for tidiness.
