### ISSUE TITLE
Cannot close image preview when opened from library window

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#108]

**Comment by jurex** [comment]
The issue is caused by the legacy window configuration instead of new UIWindowScene in the image preview library.

**Comment by jurex** [comment]
Looks like there is no easy fix for this, I probably need to write my own image preview functionality

**Comment by Splinter714** [comment]
From Discord:
>  Juraj: There are still issues on big sur when showing image details, leave it open please

**Comment by jurex** [comment]
Fixed. Switched to the new library.
