### ISSUE TITLE
Lights not visible for tokens with disabled vision

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#11]

**Comment by Zamrod** [comment]
This affects even tokens with enabled vision if their radius is set to 0

**Comment by Splinter714** [comment]
From Discord:
> Splinter: Is this still an active issue? I know it's still true, but it seems like the definition of "vision" being toggled on or off has changed with more recent updates. I'm inclined to close it.
> Tixu: I don’t see any more issue on this one. Could be closed.
