### ISSUE TITLE
Application Crashing when loading Encounter into Map

### ISSUE THREAD

**Issue by Dreyesbo** [encounterplus/encounterplus#112]
Did not see one open for this one.

Upon Encounter load, the application crashes. 

[CrashLog.txt](https://github.com/encounterplus/encounterplus/files/4463736/CrashLog.txt)
[Video of Error](https://drive.google.com/file/d/1qvw7RWHKbDXMB4S3ziEvaKZqf2b97qU1/view?usp=sharing)

**Comment by Dreyesbo** [comment]
Figured it out. The Encounter had a **'** character as a name (Nima's House). Removing it loaded the encounter.

**Comment by jurex** [comment]
Thanks for bug report @Dreyesbo !!!

**Comment by jurex** [comment]
ok, got it fixed, the issue was not in the name, but in the wrong coordinates for available position for map token (outside of the map bounds). Thanks again for report and video, it helped a lot!!!
