### ISSUE TITLE
Flying Height

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#115]
Multi part, not sure on how well they'd work apart from the token!

* Add a flying height to creatures, and include that in the token for sharing screens.
* Show some form of vertical ruler for creature heights (maybe down the edge of the screen)
* Incorporate flying height into range calculations for whether spells can affect things (needs to also know the height the spell is cast at).
* Incorporate height movement into movement calculations - possibly keep the movement per creature on-screen till its turn ends.

![image](https://user-images.githubusercontent.com/290714/79075141-cbb33e00-7ce8-11ea-9636-cf7e416a9d8a.png)

**Comment by jurex** [comment]
it will be called elevation, done
