### ISSUE TITLE
Line of Sight remembers what's been revealed and displays it greyed-out

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#119]
I would love it if LoS could remember what has been seen before, and then display the map but slightly faded where a PC had once been able to see, but now cannot. 

(Roll20 does this as an example)

Another possible implementation would be if LoS could erase fog of war permanently (and basically have the darkness form LoS "off")

Usage: Helps PCs remember the map, assuming we aren't doing a a hard-core old-school dungeon crawl where they have to map things themselves, I usually just want them to be able to see where they've gone before, even if they no longer have LoS.

**Comment by jurex** [comment]
done, with improved fog of war & exploration mode
