### ISSUE TITLE
Campaign reference tag

### ISSUE THREAD

**Issue by Team-Hufflepuff** [encounterplus/encounterplus#12]
Add a campaign reference tag to PCs so they won't be overwritten when imported from DDB.

**Comment by jurex** [comment]
rrgeorgeToday at 22:38
I’m adding a <campaign ref=“slugified-campaign-name”><campaign> tag to characters

**Comment by jurex** [comment]
done, you can add campaign references like this:
```
<campaign ref="/campaign/test-campaign" />
<campaign ref="/campaign/additional-campaign" />
```
there can be more then one reference
