### ISSUE TITLE
Option to make areas outside of Line of Sight just greyed-out instead of black on Player screen

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#120]
Similar to the Daylight feature, but let the parts that are hidden by Line of Sight be just greyed out instead of completely black on the player screen. (Just how the DM screen does, except still honoring fog of war as completely black.)

Usage: Sometimes I may want my players to see the entire map (except for Fog of War sections) however using the LoS can help quickly determine 1/2 or 3/4 cover.

Definitely just more of a nice to have since I can always just draw a line to help me with cover.

**Comment by Duseylicious** [comment]
Related to https://github.com/encounterplus/encounterplus/issues/119

**Comment by jurex** [comment]
measurement like this (cover, line of effects, etc..) would be better to handle with separate feature. measurement mode?

**Comment by Splinter714** [comment]
@Duseylicious Looks like this was addressed with 4.11.0. Closing for tidiness. Feel free to re-open if I'm missing something.
