### ISSUE TITLE
Add quick shortcus to quickly create and open new map on the tab

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#127]
Kenneth Yesterday at 20:15
I would like to request a feature. A quick Tab option, similar to an internet browser. Alt+T, or maybe with a long press on the iPad, you could quickly make a new tab and add a map on the fly, in case your players go into an area you weren't expecting them to take.

**Comment by MrWickedClown** [comment]
Perhaps have a smaller blank tab to the left or right with a + on it and tapping that adds a new one. Kind of like chrome.

**Comment by Splinter714** [comment]
This was added to app ... menu in either 4.11.0 or 4.11.1
