### ISSUE TITLE
Faster way to present a loaded map

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#131]
I would love a faster way to change which map I'm presenting.  

One idea is to add a button on the map tabs.  (to the right of the name? To the left of the 'x'?) that will switch that map to presenting on the 2nd display.

Another way could be a button next to the Display icon that simply loads whatever map tab is currently open into the 2nd display. 

I"m often in one map, I pull up another map (either actually load it, or it's already loaded and I tap the tab) and I start doing things, and I forget that I have to switch my presenting map.

An option in the settings to "automatically switch presenting map when changing tabs" could be nice too - however I think the current default is a good one so DMs don't accidentally show the wrong map, or can work on things in one map while presenting another.

**Comment by jurex** [comment]
Have you tried long press on tab and present action @Duseylicious ? should be fast enough... I need to make this more obvious.

**Comment by Duseylicious** [comment]
Ahh, no I hadn't!  And I just discovered it's right-click on mac.  

Yeah, long presses aren't always obvious.  I don't have a suggestion there beyond some sort of tool tip / intro walkthrough.
