### ISSUE TITLE
(Mac only) Dragging encounters, etc. from Library windows to the map creates a marker, but doesn't link the reference.

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#134]
On the mac I love being able to open multiple library windows while building things out.  It lets me create markers by dragging items into the map, but no matter the item type (page, encounter, etc.) the reference doesn't fill in, like it does when I drag from the search or campaign slide-in widows.

**Comment by Splinter714** [comment]
done

**Comment by Duseylicious** [comment]
Thank you!  yes I also verified, it does indeed work now.
