### ISSUE TITLE
Feature Request: Allow delete of selected objects with the Delete/backspace key

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#136]
Allow delete of select objects (both on map and in the Library) with the Delete/backspace key.  

On the Mac in particular, it would feel intuitive to be able to select something with the mouse and then press the delete key to remove it.

Bonus - (both on map and in the Library) allow Option-drag to duplicate.

**Comment by Taliesin1** [comment]
See #227 for more keyboard ideas.

**Comment by Splinter714** [comment]
Duplicate of #227 (consolidating)
