### ISSUE TITLE
Player’s items can not contain a comma

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#138]
The player’s item list cannot contain an item with a comma in its name, because Encounter splits by comma. For
Example, “Ball Bearings (bag of 1,000)”, gets split into “Ball Bearings (bag of 1” and “000)”.
I suggest either there should be a way to escape commas in item names, use a different delimiter (such as ‘;’), or use slugs.

**Comment by jurex** [comment]
implemented with simple if/else as @rrgeorge suggested to maintain compatibility:

```
if items.contains(‘;’) {
 items.split(‘;’)
} else {
 items.split(‘,’)
}
```
