### ISSUE TITLE
Zoom on Mac via mouse wheel and/or keyboard.

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#141]
Currently the only way to zoom on Mac is with a trackpad.  (Thankfully I had an extra laying around!) 

My ideal control scheme would be that scrolling up down left and right scrolls the map, and holding a modifier key like Option zooms the map. 

Also, zooming in and out with Command "+" and Command "-" would be nice.

**Comment by jurex** [comment]
There is no API for mouse wheel in current version of macOS catalyst, so we need wait for apple to add one. 

> Also, zooming in and out with Command "+" and Command "-" would be nice.

this is a good idea, will work on it, thanks!

**Comment by jurex** [comment]
duplicate to #99

**Comment by Duseylicious** [comment]
xerows had a related suggestion:

Today at 7:31 AM
Has anybody already proposed implementing panning with 2 fingers on a trackpad?
(I'm on an iPad with Magic Keyboard & Macbook Pro)

**Comment by jurex** [comment]
fixed with workaround
