### ISSUE TITLE
Make the "..." on the pop-up for a marker allow you to edit that marker.

### ISSUE THREAD

**Issue by Team-Hufflepuff** [encounterplus/encounterplus#146]
I think this menu: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/47830431/80052138-91fbe780-84df-11ea-99ba-1423a611c929.png"> 

should have a button to bring up this menu 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/47830431/80052258-e1421800-84df-11ea-8c68-803387fecb61.png">

because the "..." is what users are hitting when trying to edit markers.

**Comment by jacobjohnston** [comment]
I definitely wouldn't want to lose the ability to edit the reference from here either. Perhaps we could have two menu items off of the "..." button: an "Edit" (to edit the marker) and an "Edit Reference" (if a reference is defined)

**Comment by Splinter714** [comment]
@Team-Hufflepuff I'm thinking this request is relatively well solved by the quick menu on tapping a marker. It's not the same solution exactly, so feel free to re-open if I'm missing something.
