### ISSUE TITLE
Adding monster adds multiples of the selected type

### ISSUE THREAD

**Issue by Eomarxx** [encounterplus/encounterplus#149]
As per this short video:
https://www.dropbox.com/s/2vppv4nc7m7uzwh/Multiple%20Critters.mp4?dl=0

Sometimes clicking the load/add button when a monster is selected adds more than 1 to the encounter. I have experienced the number of added monsters was increasing over time (ie. initially noticed it was adding 2 of the selected monster type, later 4, then 5, then 6 - always an increasing number)

Killing the app and restarting solves the problem and resets the added number of monsters to 1.

**Comment by jurex** [comment]
duplicate #286
