### ISSUE TITLE
Cannot make text both italic and bold in compendium text

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#152]
Text inside `<b>` tags that are inside `<i>` loses italic formatting and is only bold.
Text inside `<i>` tags that are inside `<b>` loses bold formatting and is only italic.
In both instances the expected result should be text that is both italic and bold.

**Comment by leoincendia** [comment]
A feature request that would make this even nicer would be a shortcut to have both. I figure the item/ monster/ spells tags work this way converting to a <a> tag. No big if not, but it would be nice.

**Comment by leoincendia** [comment]
How do you get the Names of actions, traits, etc. to be bold and italic?

**Comment by jurex** [comment]
Fixed by using the markdown syntax `**_asdf_**`
