### ISSUE TITLE
[Feature request] Allow custom grid size on monsters

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#154]
Currently monsters can go all the way to Colossal (which isn't technically in 5e.)  Technically, Gargantuan, the larges size, is 4x4 _or more squares_ and can allow for even larger monsters.  I'd love to see the grid size to be able to be completely customizable. 1x2, 2x5, 10x10, etc. The drop downs for the normal sizes should still be the primary way to set size, but being able to choose "custom' and type anything in would be great.

Thanks!

**Comment by jurex** [comment]
already implemented with custom token sizes from version 4.11
