### ISSUE TITLE
Feature request- add a scale adjustment on token art

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#156]
Occasionally I will find great token art on the interwebs but the size would be slightly too big or small for what I want. Rather than having to take the token into an image editing program and add negative space to shrink it it would be nice to do in app. This would also allow some tokens to be slightly bigger than one square while keeping the technical size category.

**Comment by jurex** [comment]
good idea, thanks!

**Comment by MrWickedClown** [comment]
No problem! Just one of those great shower thoughts. I should probably do more cleaning and less thinking ;-p

- Matt

**Comment by jurex** [comment]
done
