### ISSUE TITLE
Web view LOS updates

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#160]
Various issues, perhaps related -

> D1 ||| PB: Bug report: Web Server Line of Sight.
> If a PC has LoS enabled it works fine. If I disable it or set it to 0/0 the revealed area gets stuck in the same place even after moving the PC token away. After re-enabling it the light area jumps back to the current location of the PC token. The work around I've found is to remove the PC from Initiative and add them again.

Also, if enabling LOS on the app, then everything goes black on the web-view, but moving the creates causes the web-view to update and recalculate for the moved creature.

**Comment by jurex** [comment]
fixed in #170
