### ISSUE TITLE
[Feature Request] Mac- Adjust font size of monsters/items/pages/etc

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#164]
I run E+ on a 27inch iMac, and a lot of the text is very small and difficult to read.  Im specifically talking about any of the text when you open a PC or monster from the initiative tracker, or when reading entires in the library, campaign or search tabs, opening shortcuts, etc.  The button sizes are all good, and the text that displays the names of, well, everything, is also good.

Variable master font size would be great, but I'd be happy with a just a decent bump to the size even if I couldn't adjust it.  (I have the initiative tracker set to the "large" size")

Included screenshot of what it looks like.
![Screen Shot 2020-05-21 at 6 30 35 PM](https://user-images.githubusercontent.com/63576494/82621910-42b5df00-9b91-11ea-9570-f03d6fdcf533.png)

**Comment by jacobjohnston** [comment]
+1 for this feature request. I've found this to be a common problem with Mac Catalyst apps - Apple does a weird scaling of text that makes text seem a lot smaller in the macOS app than it does on the iPad.

**Comment by Taliesin1** [comment]
Yes, please!

**Comment by jurex** [comment]
stat blocks text size bumped, also new `.catalyst` class has been added to the `<html>` tag in page template to fix font size in web view.
