### ISSUE TITLE
Code Editor in Pages Applies Unwanted Text Formatting

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#183]
The code editor for creating pages currently applies unwanted text formatting. For example, typing quotes will have them changed to from standard straight quotes to stylized smartquotes. While in the code editor, the UITextInputTraits should be changed to turn off features like smartquotes and any autocorrection.

**Comment by jurex** [comment]
I think it's already turned off, but I'll check it out again.

**Comment by Splinter714** [comment]
@jacobjohnston This is resolved, correct?

**Comment by jacobjohnston** [comment]
Yep - this looks to have been resolved somewhere along the way - closing.
