### ISSUE TITLE
Pressing Forward Delete on Page Editor deletes more than one character

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#186]
Steps to reproduce:
1. Open page editor
2. Type "This is a test"
3. Move caret to very beginning of text, before "This"
4. Press forward Delete Key (Fn-Delete on some keyboards) to delete the first character in the sentence

Expected behavior:
For the text to now be "his is a test"

Actual behavior:
Text is "s is a test"

This seems to occur on macOS systems only. Doing a forward-delete on iPadOS (which can be done with a Folio Keyboard by holding down the world key and pressing delete) seems to work fine.

**Comment by Splinter714** [comment]
@jacobjohnston mind checking macOS if this is still an issue? I only have iPadOS

**Comment by jacobjohnston** [comment]
This issue looks to have been resolved somewhere along the way - closing.
