### ISSUE TITLE
Add UPNP configuration for port forwarding

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#189]

**Comment by rrgeorge** [comment]
Apple provides a pretty straightforward framework for this: https://developer.apple.com/documentation/dnssd/1804751-dnsservicenatportmappingcreate

**Comment by jurex** [comment]
It was not straightforward at all, but I finally made it work. However, I cannot get the callback function (`DNSServiceNATPortMappingReply`) working, because it requires some special configuration on the listening socket which I cannot use in conjunction with NIO framework. Maybe there is some other solution, but the whole `dnssd` framework is very poorly documented, so I'm leaving it as is now. 

including this old code example just for a reference:
https://developer.apple.com/library/archive/samplecode/PortMapper/Listings/PortMapper_m.html
