### ISSUE TITLE
Unable to import compendium when multiple spells point to the same image

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#190]
Steps to Reproduce: 
1. Create a compendium XML where multiple spells point to the same image file (e.g. "MySpell.png")
2. Export the compendium
3. On another device (or the same device after clearing the data), import the compendium.zip file
4. Observe that E+ shows the error: The file "MySpell.png" couldn't be saved in the folder "spells" because a file with the same name already exists.

What's happening:
If you run zipinfo command on the compendium.zip file (i.e., "zipinfo -1 compendium.zip"), you'll see that the zip file is actually creating duplicate entries for each instance of the spell that includes that image.

**Comment by jurex** [comment]
fixed
