### ISSUE TITLE
Marker Context Menu Sometimes Doesn't Appear on macOS

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#192]
Steps to Reproduce:
1. Starting with a blank slate (no open maps other than the default one)
2. Create a new map (I left mine blank, no items on it)
3. Add a marker to the map (I labeled mine "My Marker")
4. Save the Map
5. Quit E+
6. Open E+
7. Go to the new map and edit it
8. Note the context menu for the marker (i.e., with "Edit", "Copy", "Delete") will not appear

At this point, adding a new marker WITH A LABEL will resolve the problem and make all the context menus work. Creating a marker without a label is not good enough to workaround the issue.

This can be reproduced on a map with any number of markers. It seems to be the act of opening E+ and proceeding straight to a map editor that breaks the marker context menus.

**Comment by jurex** [comment]
fixed with new context menus (longpress/rightclick/standard)
