### ISSUE TITLE
Unable to change Module Item parent on macOS with third party mice.

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#193]
The problem:
Currently, the only way to change grouping on module items (e.g., pages and maps) is to use the swipe actions on the table cell and choose "Edit". This works fine on macOS if you have a magic trackpad or magic mouse, but if you use a third party mouse (e.g., any logitech mouse), there is no way to invoke the swipe action.

Possible Solutions:
You'll think of the best solution for this, I'm sure, but two possible solutions I thought of were:
1. Add a context menu to the row that duplicates the actions exposed through swipe. See tableview context menu sample code below.
2. Find some alternate way of programmatically exposing the swipe menu (e.g., long press). Not sure if this is actually possible, I've never done it.

UITableView Context Menu code:
```swift
    /// Gets the context menu configuration for a specified row
    func tableView(_ tableView: UITableView, contextMenuConfigurationForRowAt indexPath: IndexPath, point: CGPoint) -> UIContextMenuConfiguration? {
        return UIContextMenuConfiguration(identifier: nil, previewProvider: nil, actionProvider: { _ in
            return self.createContextMenu(at: indexPath)
        })
    }

    /// Creates a context menu for a specified index path
    /// - Parameter indexPath: The index path of the context menu
    private func createContextMenu(at indexPath: IndexPath) -> UIMenu {
        let editAction = UIAction(title: "Edit") { [weak self] _ in
            // Do something here
        }
        return UIMenu(title: "Options", children: [editAction])
    }
```

**Comment by Duseylicious** [comment]
I think being able to drag & drop for organizing would be the ideal solve for this.  I understand if there are complications implementing that quickly, though.

**Comment by jacobjohnston** [comment]
It looks like, as of 4.11, there is now a context menu on these items so this is no longer an issue. From my perspective, this closes the issue, though I think @Duseylicious has a good suggestion here we may want to track as a separate enhancement request.

**Comment by Duseylicious** [comment]
There is a request for my idea, here https://github.com/encounterplus/encounterplus/issues/135 👍
