### ISSUE TITLE
Tutorials Kick to Safari/Don't Load

### ISSUE THREAD

**Issue by HighFiv-e** [encounterplus/encounterplus#195]
As a user, I would like to see and play all tutorials within the app.

**Current Behavior**
- Click ? mark
- Click Tutorials
- Exits app and opens safari
- Reopening the app, no video embedded objects load

**Acceptance Criteria**
- Prevent opening in Safari/External Browser
- Mimic behavior of Help > Quickstart with showing video in modal

**Comment by jurex** [comment]
fixed
