### ISSUE TITLE
Add pasteboard support to Background image

### ISSUE THREAD

**Issue by simonward** [encounterplus/encounterplus#20]
Add "Paste" to the Background image alert if there’s an image on the Pasteboard.

**Comment by simonward** [comment]
![background_alert](https://user-images.githubusercontent.com/1904698/74079380-765a6800-49eb-11ea-9efc-db72b1de5629.jpeg)

**Comment by simonward** [comment]
`let generalPasteboard = UIPasteboard.general
if generalPasteboard.hasImages {
    if let image = generalPasteboard.image {
        print(image)
    }
}`

**Comment by jurex** [comment]
Done
![Simulator Screen Shot - iPad Pro (11-inch) - 2020-02-11 at 16 05 26](https://user-images.githubusercontent.com/925257/74248787-6cd14880-4ce8-11ea-92b2-c8ef26805e92.png)
