### ISSUE TITLE
Add Section for Lairs (Lair Actions & Regional Effects)

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#201]
Add support for entering Lair information on Monsters: Lair Actions and Regional Effects

**Comment by Splinter714** [comment]
Ideally pair actions would somehow have separate initiative marker at the top of the initiative order

**Comment by jurex** [comment]
So this is implemented in description field (markdown supported) which can be revealed by swipe action in combat. I need to add som custom functionality to address initiative order, but probably in new ticket.
