### ISSUE TITLE
[bug] dd2vtt import alignment off

### ISSUE THREAD

**Issue by ep1cman** [encounterplus/encounterplus#205]
It seems that when importing from Dungeondraft the walls/doors have a slight offset meaning doors can’t be seen properly from one side.

![08A0BD85-BFA2-42CE-AD7F-9B6476ED865D](https://user-images.githubusercontent.com/5303409/83955992-cdb0fd80-a850-11ea-9ed7-8223c704349f.jpeg)

**Comment by ep1cman** [comment]
It seems the walls line up with the encounter+ grid which is equally offset. (DD grid = black, E+ grid = blue)

![FB631F4C-B3E2-4209-BE4C-43D6F07866CB](https://user-images.githubusercontent.com/5303409/83956022-431cce00-a851-11ea-9f20-3a8f109735d5.jpeg)

**Comment by ep1cman** [comment]
Upon some further investigation it seems to be an issue with the scaling of the image. After import the grid is set to 69 pixels, which is slightly too small and this progressively gets worse as you travel down/right. Changing it to 70 is too big. It seems there is a map image size limit and the automatic downscaling isn't quite perfect.

**Comment by jurex** [comment]
There are multiple factors. First is the maximum image size in E+ is 4096x4096 px, so dungeondraft map needs to be scaled if it's above. Then the device screen ratio (1 logical point could be 3 physical pixels) and number rounding. Easy solution is just to export your map to match 4096px limit or use image scale in E+ to align it properly. I'll try to improve it though.

**Comment by jurex** [comment]
improved a bit by bumping the maximum map size #298
