### ISSUE TITLE
The Restore Default option says it will delete existing data but doesn’t

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#206]
The Restore Default option in settings says it will delete existing data, but it does not. I prefer it’s current function, where it just simply imports the Open Game Content. But if it should be deleting and clearing out the compendium first, then it is not functioning properly.
This message should either be changed or the functionality should be changed to match the message. I prefer that the message just be changed to say something along the lines of “Any existing changes to Open Game Content entries will be lost”

**Comment by jurex** [comment]
Message changed to "Do you want to restore default \"Open Game Content\"? Any existing changes to Open Game Content entries will be lost."
