### ISSUE TITLE
[Feature Request] Load data into app from JSON source

### ISSUE THREAD

**Issue by lambersond** [encounterplus/encounterplus#208]
It would be nice to have to ability to load compendium material from JSON sources as well as XML. 

There are a [lot of good JSON source materials](https://github.com/TheGiddyLimit/homebrew) and it would be nice to be able to port them directly in.

**Comment by jurex** [comment]
I'm planning to switch to JSON and ditch XML very soon. XML in E+ is mostly for compatibility reasons. Thanks!
