### ISSUE TITLE
Feature Request: Ping point of interest

### ISSUE THREAD

**Issue by timbomckay** [encounterplus/encounterplus#213]
I know the DM has the ability to highlight an area, but as far as I can tell the players don't have a way to interact with the map. Roll20 has a nice feature for the players to ping a point of interest, to say _"what do I see in this bush here"_ and a ring expands for all viewers to see.

![Image of Roll20 Ping](https://wiki.5e.tools/images/e/e7/R20esAutoPing.gif)

This can kinda relates to this request in regards to web-client: #165

**Comment by timbomckay** [comment]
Nevermind, I was testing on the immediate external display and not the website. I see the highlight option now.

![](https://media2.giphy.com/media/xT0BKFyZt9MMx9xkpW/giphy.gif?cid=ecf05e47e76cfe05e55855d3365cdc0c9e9a4b402a9dd5cf&rid=giphy.gif)

**Comment by jurex** [comment]
no worries @timbomckay
