### ISSUE TITLE
[Feature Request] Fit screen button next to zoom buttons

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#214]
i use the "fit screen" option often.  It'd be nice if there was a "fit screen" button right next to zoom buttons on the battle map, to be able to quickly fit a newly loaded map.  Bonus for adding a keyboard shortcut to do the same.  (command-0 is a common "fit screen" shortcut, with command + being zoom in and command - being zoom out.)

**Comment by Splinter714** [comment]
Consolidating with #28
