### ISSUE TITLE
[Feature Request] Give "show token's artwork" separate options for DM view and player/webview

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#215]
There are times when one screen is more legible than another.  Maybe playing on a smaller than normal TV with the second screen, etc.  It'd be nice to choose whether or not to show token artwork independently for the DM side vs the Player/web side.  

I self-admit, this is low priority, but thought I'd submit the idea while I had it.

Perhaps a better long term fix would be app-wide font size adjustments.  The theme for me seems to be "when playing on a large monitor on my mac, I can't read most of the text very well."  :)

**Comment by jurex** [comment]
removed show `token's artwork` option entirely because of the new workflow
