### ISSUE TITLE
[Feature Request] Rearrange order of map settings fly out options

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#222]
One of the first things a user tends to do when making a new map is adding a background image (if they are going to use one).  Moving this option up in the menu where it is visible would make it easier to find.  

I'd suggest this order
image/video and scale
Grid align, and grid options
Fog and LoS options

Thanks!

**Comment by MrWickedClown** [comment]
I would go one step farther and also suggest a “new map wizard” of sorts that asks what size/color you want the background or if you want to pull in an image for the map. Then if they chose an image walk it through the steps of grid align/scale. Then give the option for FOW/LOS before finishing. It’s the first steps we all do each time we add a map, why not walk you through it. It also gives those using the “blank map” the option of a different color background :)

**Comment by jurex** [comment]
re-organised. while the wizard is a good idea, it will take too much time to implement. will revisit the idea later if necessary... thanks all
