### ISSUE TITLE
Ability to filter NPCs

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#228]
It would be nice to have a way to clearly filter by (or exclude) NPCs in the compendium.
Possible solutions:
- Add a filter to filter by Role, possibly by default set to *enemy*
- Move NPCs in the monsters compendium to a separate NPC section
- Have another section, in addition to Monsters, Players, Items, and Spells, for NPCs.

Related to #34 & #88

**Comment by Tixuoty66** [comment]
I would like an ability to filter by 'Source' too, which is not a field at the moment (ex : PHB, Xanathar, COS, Homebrew...) and then ability to export only the filtered Compendium.

**Comment by jurex** [comment]
done
