### ISSUE TITLE
[Feature Request] Roll tables

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#229]
From Milamber:
A rollable table thing would be great, for instance, if you needed an npc quickly, and it throws out some options from some tables you’ve set.
In know there’s tools like donjon but being able to have that and setting a “make extra npc” shortcut would be incredible

https://discordapp.com/channels/565243968858751027/634387773872275466/727251776847216641

______
Dusey's notes: Pages seem like a good place for these, but that's just off the top of my head.  They mention for NPCs, but there are of course things like random encounter tables that would be nice.  There could be a dedicated UI for those similar to the random encounter generator.

**Comment by Taliesin1** [comment]
Adding to this: please allow subtables and allow us to upload CSVs to create a table. In addition, it would be awesome to be able to attach a table or tables to tiles or tokens — make them accessible via a little drop-down menu or something.

**Comment by jurex** [comment]
done
