### ISSUE TITLE
Importing a page with the same UUID as an existing page does not replace that page.

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#232]
Scenario: Using the module packer, a user creates a page with a specific UUID. Later, the user modifies that page, repacks the module with the same ID as before, and tries to import a newer version of that page. The page does not seem to be replaced in that case - instead, the page in the import seems to simply be ignored.

**Comment by jurex** [comment]
looks like there is a problem with content cache, need to investigate this further, thanks @jacobjohnston

**Comment by jurex** [comment]
yeah, it was a cache problem. fixed
