### ISSUE TITLE
[Feature Request] Option to save file to location when exporting / sharing, on Mac

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#233]
On Mac, choosing to export an entry or share something brings up the share sheet.  There are times when this is handy, however I'd prefer an option to choose a location on my mac to save the file to.  Right now I have to send the file to email or notes, and then move it from there.

If there is a way to do both, that'd be great (share sheet and option to just save the file) but if I had to choose only one, it'd be to replace the share sheet with the standard save dialogue box. 
![Screen Shot 2020-07-01 at 9 44 52 AM](https://user-images.githubusercontent.com/63576494/86270534-3c4b5780-bb80-11ea-9887-40244d70fa02.png)

**Comment by jurex** [comment]
Sigh, I don't understand why this is not automatically translated to file save on macOS. Will check it out, thanks @Duseylicious

**Comment by jurex** [comment]
this is already implemented, closing
