### ISSUE TITLE
[Feature Request] Polygon tool for lines (esp. for walls)

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#236]
SnizzleLiveToday at 10:36 PM
A polygon-tool would be nice for wall creation and other such tasks. You click somewhere and it creates a node, next click creates the next node and so on. An added bonus would be to drag and drop the nodes dynamically :)

**Comment by jurex** [comment]
walls drawing will be changed soon, stay tuned!

**Comment by jurex** [comment]
this is part of the new wall drawing engine
