### ISSUE TITLE
Encounters with NPCs don’t save with NPCs with a role other than ‘enemy’

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#238]
Encounters with NPCs with a role other than ‘enemy’ don't save with the NPCs. 
However, Encounters that contains a creature with marked as friendly do save.
Maybe it would be best to have the ‘role’ field set the creature the same way as marking them friendly does?

**Comment by Splinter714** [comment]
@rrgeorge this appears resolved, no? re-open if I'm missing something
