### ISSUE TITLE
[Feature Request] More robust undo

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#243]
AFAICT, the undo button only removes the last thing drawn.  It'd be great to have a very robust undo that would undo all sorts of actions.  The main one being to undo deleting a drawing or asset that was put on the map, but also undo moving drawings and assets, rotation, size, area effects, etc.

**Comment by jurex** [comment]
yeah, undo is pretty shitty now, I need to rework it from the ground. thanks!

**Comment by jurex** [comment]
better undo is now part of new wall drawing/rendering engine. other parts will follow soon
