### ISSUE TITLE
[Feature Request] Quick deleting and/or hiding of creatures while initiative is active

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#245]
Sometimes I want to remove a token after they have died, or perhaps because one of them ran away, or any other number of reasons.  currently, I have to stop initiative in order to delete the tokens.  I'd like the option to delete them immediately.  I realize this does mess with XP awards.  

My goal is to remove them from the map and/or initiative, quickly, because the screen or initiative bar i cluttered with a lot of enemies. Maybe a quicker way to hide them (long press map token and get the option to hide, or add hide to the context menu when you long press initiative bar, or maybe add hide to the swipe gesture in the initiative bar, I don't know.) Ideally it'd be something that can be done quickly from the map token.

**Comment by Rycochet** [comment]
Set them to Hidden ?

**Comment by Duseylicious** [comment]
> Set them to Hidden ?

So, I guess in heart I’m getting at two different things.
1.) why can’t I delete baddies mid-combat?  I constantly have to switch in and out of combat to do so.
2.) I use hide often, and currently it’s a 4-step process (swipe, edit, hide, save) and I’d love for it to be 2 steps. (Swipe, hide.   Or long-press, hide.)

**Comment by Rycochet** [comment]
Yeah - deleting should probably have something about awarding the XP as an option during combat, but definitely need something quicker and easier for Hidden I think :-)

**Comment by jurex** [comment]
You can delete any token any time with the popup menu (longpress on iOS, right click on macOS) @Duseylicious . Hide action would be useful there though.

**Comment by DHCross** [comment]
> You can delete any token any time with the popup menu (longpress on iOS, right click on macOS) @Duseylicious . Hide action would be useful there though.

This is not working for me on my Ipad Pro with longpress.

**Comment by Duseylicious** [comment]
> > You can delete any token any time with the popup menu (longpress on iOS, right click on macOS) @Duseylicious . Hide action would be useful there though.
> 
> This is not working for me on my Ipad Pro with longpress.

It’s working on my iPad Pro- make sure you are long pressing them in the initiative tracker, not the token itself.  (I’d love for it to b\e on the token proper somehow.)

**Comment by jurex** [comment]
done, with the new token workflow
