### ISSUE TITLE
[Feature Request] Make Client URL copy-able

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#247]
From kinkofer:

![Screen Shot 2020-07-09 at 11 06 36 PM](https://user-images.githubusercontent.com/63576494/87122019-dffbce00-c238-11ea-9d68-7f28d790f2b6.png)

**Comment by Duseylicious** [comment]
Related to https://github.com/encounterplus/encounterplus/issues/233 which is requesting changes to the share sheet.

**Comment by jurex** [comment]
fixed
