### ISSUE TITLE
Additional token image for creatures

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#25]

**Comment by jurex** [comment]
Maybe a link to asset

**Comment by MrWickedClown** [comment]
On a related note: Could we have the ability to add an encounter specific token/art? Maybe you are using the bandit as a pirate, but don’t want to creat another entry but want them to look like a pirate. Or the token is a dude and the story has it as a lady (or vice versa). I think this could be in the same “edit creature” screen with the label and name override.

**Comment by MrWickedClown** [comment]
Also, support for multiple tokens on a creature and randomize them when added to an encounter for variety

**Comment by Rycochet** [comment]
@MrWickedClown Depending how complicated it wants to be - could have a map of token artwork with weights, so it's chosen at random (default weight simply 1/x) - but could have some "special" artwork that has a weight of zero... Then when setting up the encounter can have it part of the edit panel to allow the DM to choose any of the available tokens easily :-)

**Comment by Splinter714** [comment]
@MrWickedClown is the "alternate art" request satisfied by the current app version? Or is there something I'm missing?

> On a related note: Could we have the ability to add an encounter specific token/art? Maybe you are using the bandit as a pirate, but don’t want to creat another entry but want them to look like a pirate. Or the token is a dude and the story has it as a lady (or vice versa). I think this could be in the same “edit creature” screen with the label and name override.

**Comment by MrWickedClown** [comment]
Yes, this should all be handled with the current version. :)
