### ISSUE TITLE
IPv6 Address formatted incorrectly

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#253]
The server url is formatted incorrectly. It’s url-encoding the `:` in the IPv6 address to `%3A` which cause safari to have an aneurysm. Changing them back to `:` works.
This also may be an issue with the web-client issue, but I cannot verify since the web-client can't seem to connect to IPv6 addresses at all see: encounterplus/external-screen#54

**Comment by jurex** [comment]
fixed
