### ISSUE TITLE
Visual indicator - portion of screen on TV

### ISSUE THREAD

**Issue by Zamrod** [encounterplus/encounterplus#26]
Some sort of visual indicator as to which portion of the iPad or iPhone screen is being sent to the external screen so that you know what everyone else can see even if you can’t see the external screen well. Maybe make it a dotted line or something. It should be subtle and maybe have a button to turn it on and off.

**Comment by Rycochet** [comment]
Relevant to this - I run on an iPad mini in portrait, and external to a larger screen in landscape - so there's actually more on display externally than I can see - so in that case should it show the outline, or should it just not show anything (and disable the button)?

**Comment by Rycochet** [comment]
As an extension to this - when using the web client, show what each of the players can see, with a ghosted box of their selected colour. This can let you know that everyone is looking at the right area of the map.

**Comment by Splinter714** [comment]
From #275 @maxlds

> When a DM is using the iPad as the primary screen and the players are using a secondary screen via HDMI/Airplay, sometimes it is difficult for the DM to know what the players are seeing since the aspect ratio from the iPad to the external screen may be different and the external screen could be landscape or portrait. It's quite often that I have to look at the player screen to zoom and recenter to make sure I'm showing them what I intend to show them.
> 
> It'd be fantastic to show a box on my iPad that shows the borders of the TV screen that the players see so I can see what is on their screen. It would be nice if the DM could enable the overlay on the screen, choose the aspect ratio and have it synced with the landscape/portrait option for external screen.
> 
> See attached - red corners show extent of what external player screen sees.
> 
> ![image0](https://user-images.githubusercontent.com/51212235/88974744-5909a680-d276-11ea-882b-d7da20b2155a.jpeg)

**Comment by jurex** [comment]
So, this one was really complicated. Syncing viewports across multiple windows and the web client camera is no fun. Offset, relative screen movement, scaling... ugh... Had to re-implement almost everything related to the external screen map camera movement. But it was well worth, now the code is more clean and modular. 

![image](https://user-images.githubusercontent.com/925257/130613027-fdf4f0c9-343e-408c-b153-cbd63b988992.png)

**Comment by jurex** [comment]
Right now it's limited only to one external screen viewport, but can be expanded in the future. closing for now
