### ISSUE TITLE
Messages window will duplicate messages sometimes

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#260]
If the messages window is open, and two messages are sent simultaneously (i.e. a dice roll and a text message) one message will be displayed twice.
Closing the window and reopening it shows the correct 2 messages. If the messages window is not open, the notifications are correctly displayed.

**Comment by Splinter714** [comment]
@rrgeorge I'm struggling to reproduce this one. Have you seen it lately?

**Comment by rrgeorge** [comment]
This is a really tricky one. The two api messages have to be simultaneous. I’ll have to specifically setup a test to confirm it or not.

**Comment by Splinter714** [comment]
But at least not known to have been directly fixed, so could probably be moved to low-priority and reviewed 4.11.1?

**Comment by rrgeorge** [comment]
This issue still persists, but is intermittent. Tested with the following x3:
```
curl -X POST -d '{"source":"Test","type":"roll","content":{"formula":"1d6","result":3,"detail":"3","name":"Test"}}' http://ipad-ip-address:8080/api/messages & curl -X POST -d '{"source":"Test","type":"message","content":"Test"}' http://ipad-ip-address:8080/api/messages
```
With the messages window open, I get:
![9357467A-467F-49D1-B900-74DC3C37EECE](https://user-images.githubusercontent.com/8526392/116792278-7ae9c100-aa74-11eb-936a-eb7a878c6b2e.jpeg)

After closing and reopening the window:
![9E90F4AD-3068-48C1-8915-1CEBCD96D389](https://user-images.githubusercontent.com/8526392/116792291-8ccb6400-aa74-11eb-84aa-7aa48a1332e3.jpeg)

**Comment by jurex** [comment]
I think i found the root cause, thanks @rrgeorge for steps!! It was caused by the race condition during collection view batch update (it was too slow to update when app received multiple messages at the same time). Solved it with the new diffable data source, which is working with data snapshots rather than raw data collections from realm db.
