### ISSUE TITLE
Line edit functionality

### ISSUE THREAD

**Issue by japandian** [encounterplus/encounterplus#262]
A nice feature would be to enable the ability to set feature of drawn lines, such as:

- Opacity on or off

- Pass-through on or off

This would enable small windows to be seen though, but not passed through, in the way the blue line currently denotes a portal or a red line denotes a wall.  This could also work well for secret entrances.

**Comment by jurex** [comment]
invisible walls, secret doors, done. Opacity is hard to do when using vector based line of sight.

**Comment by japandian** [comment]
Check your Discord DMs.  I have something I want to offer up to the community.  

Thanks! 

Scumbag

 

On 9/21/20, 9:20 AM, Juraj wrote:

 

Closed #262.
