### ISSUE TITLE
Button to sync external screen to 1 inch

### ISSUE THREAD

**Issue by Zamrod** [encounterplus/encounterplus#27]
Add a button to set to external screen to 1 inch squares and lock the external screen from zooming in and out.

**Comment by Rycochet** [comment]
Possible implementation detail - "Save / Load external scale", possibly with multiple presets - maybe also needs a "Lock position" too - but would let people put their mini on the external, or just choose something that works for their setup :-)

**Comment by jurex** [comment]
done
