### ISSUE TITLE
Feature request: Longpress options on tokens

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#270]
I feel like there should be a long press menu for tokens for things like:

rotation- maybe adds the little blue dot for turning like on assets until you click away 

size- maybe has a drop down with sizes or just a +/- to move up and down sizes 

hide/unhide- similar to assets
 
Add light source- ability to add darkvision or torch as a temporary addition

I know most of these things are possible now, but getting them to the top level would be amazing and save time. Also, I believe long press gets assigned to right click on Mac and iOS with mouse so it seems like a natural addition without cluttering the UI.

**Comment by jurex** [comment]
done

**Comment by jurex** [comment]
possible duplice of #173

**Comment by jurex** [comment]
yay, still missing hide/unhide. will skip size, because it's more complicated now, and rotation will be handled by gesture recognizer

**Comment by jurex** [comment]
done
