### ISSUE TITLE
Feature Request - Ability to name Auras in Character

### ISSUE THREAD

**Issue by japandian** [encounterplus/encounterplus#273]
I'd like to be able to edit preloaded auras to their assigned asset/condition within the character to allow for quick access in-combat.

**Comment by rrgeorge** [comment]
You can already do this. When you edit the aura, under the Parameters section, there is a name field.
![image](https://user-images.githubusercontent.com/8526392/88837226-d48f2900-d18c-11ea-93e4-3961432edc50.png)

**Comment by japandian** [comment]
Jesus.  I’m an idiot.  Thanks!

Scumbag Carl
