### ISSUE TITLE
Groups fail to load when referenced in pins on a map

### ISSUE THREAD

**Issue by mchisolm0** [encounterplus/encounterplus#276]
When I add a marker to a map and select a reference, the contents of the reference fail to show when selected. In other words, if I click on the marker, it shows an empty pop up box rather than one with the appropriate maps/pages/etc.

**Comment by mchisolm0** [comment]
Here is a picture for reference.

![](https://cdn.discordapp.com/attachments/654637454246019092/738554956835192872/image.png)

**Comment by jurex** [comment]
fixed
