### ISSUE TITLE
[Bug] On Catalyst, Library view's close button gets disabled.

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#280]
The macOS red-circle close button gets disabled occasionally on the macOS app version. When this happens, CMD-W also cease to close the window. I have not yet been able to track down a reliable way to reproduce this issue. Currently, pressing the "X" button above the Library title will still close the window, so that serves as an adequate workaround.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1703107/89434164-1291cd00-d6f8-11ea-8eb4-71558f0ef718.png">

**Comment by jacobjohnston** [comment]
Update: I have figured out what is causing this and how to reproduce it:
1.) Click on the menu with the dice roller, campaigns, etc. Do not close the context menu!
2.) Click on the Library button.

It seems the presence of the context menu is disabling the close button. I suspect closing any context menus when clicking the library button would resolve the issue. See screenshot.

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1703107/89434813-da3ebe80-d6f8-11ea-907f-4ef6971dccf8.png">

**Comment by jurex** [comment]
fixed, thanks @jacobjohnston for insight.
