### ISSUE TITLE
Inconsistent message date format between websocket and web api

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#283]
E+ sends the message creation date in RFC3339 format for the web api, but sends the mach absolute time over the websocket. This results in dates for messages received over the websocket to be close to the unix epoch rather than current. Reloading the webclient, causing a fetch of the messages from the api, causes the dates to display correctly.

**Comment by jurex** [comment]
caused by incorrect encoding strategy for messages. fixed, now it's all `iso8601`
