### ISSUE TITLE
Bug: App crashes, when adding rotation component to area effect.

### ISSUE THREAD

**Issue by EcoHeliGuy** [encounterplus/encounterplus#284]
When creating a spell area effect that rotates, multiple duplicate component entries are populated. Deleting one crashes the application.

@rrgeorge also reproduced the same bug independently. 

Video: https://share.icloud.com/photos/0zQW0_P2v01mSrylCgagBI6fg

**Comment by jurex** [comment]
fixed. this one was tricky, thanks @EcoHeliGuy and @rrgeorge
