### ISSUE TITLE
Encounter Plus will not import file if launched from files

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#285]
If EncounterPlus is not currently running, Launching it by opening a file with EncounterPlus does not import the file upon launch. Opening a file with EncounterPlus while it’s currently running will import the file as expected.

**Comment by jacobjohnston** [comment]
There used to be a similar issue when opening from Finder on macOS, but that was resolved in 4.11. However, I can confirm this still seems to be an issue with Files on iOS.

**Comment by jurex** [comment]
I've added proper url handler after cold start.
