### ISSUE TITLE
[Bug] Circular dependencies delete pages/groups

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#287]
When creating a circular reference using the "Parent" value of a page or group, the items will just disappear.

Steps to reproduce
1. Create a group
2. Create a page in that group
3. Reassign the "Parent" of the group to the page. Observe both page and group disappear.

Expected behavior:
EncounterPlus should prevent such behavior (either prevent the Page from being selected as a parent, or ignore the request and show an error message)

**Comment by jacobjohnston** [comment]
Confirmed this still occurs in 4.11

**Comment by jurex** [comment]
fixed in UI
