### ISSUE TITLE
Filter.hsb component not working on mac

### ISSUE THREAD

**Issue by joelohrum** [encounterplus/encounterplus#292]
Adding the filter.hsb component doesn’t seem to work on my MacBook. Running the Big Sur beta, if it matters. 

I’ve attached two screenshots. The image with the desaturated (white) cloud is from my iPad - I desaturated a green cloud token using the filter.hsb component to make steam.  The green version is from my mac - the component didn’t work.

![4C15597C-7D1A-4A8A-972D-17A35D9A1C35](https://user-images.githubusercontent.com/14303860/91517889-eadbf200-e8bc-11ea-8031-a74a4bc0f640.jpeg)
<img width="111" alt="9259B8A6-CBB0-4C12-B320-4B5108C01887" src="https://user-images.githubusercontent.com/14303860/91517891-ec0d1f00-e8bc-11ea-958b-abe4890052c7.png">

**Comment by rrgeorge** [comment]
Looks like it’s limited to Big Sur. The hsb filter appears to work correctly on Catalina.

**Comment by jurex** [comment]
I'll wait for the official Big Sur release then.

**Comment by jacobjohnston** [comment]
This seems to work fine in the latest Big Sur builds with E+ 4.11.1. If you see this behavior again, don't hesitate to reopen the issue.
