### ISSUE TITLE
Tokens in initiative list get mixed up

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#301]
See attached photo
![9C743E67-3D09-4036-8795-1F8316FF6999](https://user-images.githubusercontent.com/8526392/93488967-cff90e00-f8bb-11ea-925f-ded4f96c2ebd.jpeg)

**Comment by jurex** [comment]
fixed

**Comment by rrgeorge** [comment]
Reliable steps to reproduce:
1. Add a player to combat with a token image,
2. Add a creature to combat without a token image
3. Roll initiative for each
4. Start the encounter
5. Stop the encounter

**Comment by jurex** [comment]
fixed, thanks @rrgeorge for reliable steps to reproduce!!
