### ISSUE TITLE
Add video events to websocket api

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#302]
Add play/pause and timecode-sync events over the websocket for video maps
For timecode-sync, I think it there should be a button in E+ to manually synchronize the timecode of the active web-clients
Also, the web client could send a request for the current timecode when it’s finished loading the video, to synchronize itself.

**Comment by jurex** [comment]
done, E+ will send this event each time you play/stop video.
```js
{"name":"mapVideoControlUpdated","data":{"state":"play","time":23.997555555555557}}
```

**Comment by rrgeorge** [comment]
Perfect
