### ISSUE TITLE
Feature Request: Indicator of which map is being presented

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#303]
It would be helpful to have some kind of indicator, like an icon, on the tab of whichever map is being presented.

**Comment by Duseylicious** [comment]
Relatedly, some way of letting the user know they can long press for options on the tab, or something to press to bring up said options so it's more obvious, would be great.  ( https://github.com/encounterplus/encounterplus/issues/131 for context )

**Comment by jurex** [comment]
![image](https://user-images.githubusercontent.com/925257/106913673-8727e180-6704-11eb-972a-0138fe50efb9.png)
