### ISSUE TITLE
[Feature Request] Add ability to save positions of all current tokens to coordinates in an encounter

### ISSUE THREAD

**Issue by mattd** [encounterplus/encounterplus#312]
Provide some UI for saving X,Y coordinate values to an encounter based on where those tokens are currently positioned on the map.

I imagine this is actually quite a bit harder than it looks at first blush, since you have a lot of edge cases to deal with - e.g. when an encounter is used with a map other than the one on which coordinates were set, what to do with additional monsters added ad hoc, etc.

**Comment by Duseylicious** [comment]
May be related to https://github.com/encounterplus/encounterplus/issues/48

**Comment by jurex** [comment]
next version will change the entire workflow regarding tokens and creatures in combat. tokens will be part of the map, so you don't need to create a separate encounter each time you wanna save a game. closing this for now. thanks for feedback!
