### ISSUE TITLE
Public rolls when connected to an external screen not visible to DM

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#315]
When using the 3D roller, the results are normally shown at the top of the screen. When connected to an external screen, 3d dice rolls show on the external screen as expected, but so do the results at the top and in the bottom left corner, with nothing displayed for the DM. I propose that the results at the top of the screen should remain on the DM screen even when 3D dice are displayed on the external screen, since the external screen also displays a notification in the bottom corner.

**Comment by jurex** [comment]
so, I've cheated a bit by using a standard notification alert, hope it will be enough 😁
