### ISSUE TITLE
Marker contents no longer showing on tap/click

### ISSUE THREAD

**Issue by mattd** [encounterplus/encounterplus#317]
When tapping a marker, the marker now turns grey on the first tap. On second tap, the Edit/Copy/Delete tooltip appears. A third tap, the marker returns to the grey state. The marker contents modal is never displayed.

**Comment by jurex** [comment]
reference is probably pointing to the wrong (non-existing) location. I did some UX changes in this release, and I'm pretty sure they will work fine now if configured properly. Thanks!
