### ISSUE TITLE
Exporting module fails when the selection was searched for

### ISSUE THREAD

**Issue by mchisolm0** [encounterplus/encounterplus#318]
User: mchisolm0

The export will consistently fail to offer to save the export if I have used the search function to find and select the desired module. 

I have made a screen capture at the iCloud link provided below (shared 10/4/2020). 

[https://share.icloud.com/photos/0haYoT1Jed--3AauTNWfmpqBA](url)

**Comment by jurex** [comment]
sigh, looks like it's a bug in catalyst, where app is unable to dismiss presented view controller when the search controller is active. fixed with workaround
