### ISSUE TITLE
Feature Request: Ability to link a pin to a section of a page

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#319]
I’d like to be able to link a pin to a section of a page. I can already create links specific sections using url fragments and ids (`<a href="/page/page-name#section1">Section 1</a>` will link to `<h3 id="section1">Section 1</h3>` within `page-name`), but there is currently no way to specify a fragment on the reference for the pin.

**Comment by rrgeorge** [comment]
Correction. Links to fragments work within the same page, but not another page. So, `<a href="#section1">Section 1</a>` will link to `<h3 id="section1">Section 1</h3>` within the same page, but `<a href="/page/other-page#section1">Section 1</a>` will just take you to the top of other-page, not jump to `<h3 id="section1">Section 1</h3>` on that page.
So, additionally, I’d like to request the ability link to sections via fragments from other pages as well as pins.

**Comment by jurex** [comment]
done. this feature is still very experimental though, and should receive a better care in the future. url fragments are working now in page links as expected. I've added a special swipe edit action into marker reference field so you can manually edit the link and add fragment or change it. Reference URL should be working with all internal objects, but not for web sites.
