### ISSUE TITLE
[Bug] assets lost when copying map of assets not in pack

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#324]
If you move a map between modules any asset that does not reference an asset in your compendium gets replaced with a black X. 

I believe This happens if you import a module that has assets you do not have, or if you delete an asset from your compendium after adding it to a map. In both of these situations it only happens when moving to another module. 

Strangely enough there is no issue when copying to your campaign with the copy and open function.

**Comment by Duseylicious** [comment]
I had this same issue by doing the following.(tested on map.)

Make a map in a campaign. (I made a copy of one I already had.)  Drag a random asset from a webpage into the app. Move the map (swipe - move) into a different campaign.  Close the tab and re-load the map from it's new location.  The added asset becomes a black X. 
![Uploading Screen Shot 2020-10-10 at 10.09.41 PM.png…]()
![Uploading Screen Shot 2020-10-10 at 10.13.37 PM.png…]()
![Uploading Screen Shot 2020-10-10 at 10.14.00 PM.png…]()

**Comment by jurex** [comment]
fixed, thanks guys for detailed info
