### ISSUE TITLE
[Bug] Copied monsters from initiative window do not have tokens when using Asset pack for tokens.

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#326]
I love the ability to have randomized tokens when pulling in tokens and it all seems to work well when pulling in from the compendium or loading an encounter.

I did find that using the copy function in the initiative window will not use the same logic and instead uses the default circle token generated from the artwork.

**Comment by MrWickedClown** [comment]
Example image :)
![image](https://user-images.githubusercontent.com/61415452/95770807-95e31800-0c7f-11eb-8a18-8d58f4c1e310.jpeg)

**Comment by jurex** [comment]
fixed, thanks for insight!
