### ISSUE TITLE
[Feature Request] Additional Grid Customizations

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#327]
Per user Shidara on discord:

Just thought of gridline options that might be helpful:
• Adjustable line thickness
• The option to only show the intersections of lines as small crosses rather than complete lines
• Rather than using a color, making gridlines a % darkness or lightness of the pixels underneath

**Comment by MrWickedClown** [comment]
Also maybe an opacity option

**Comment by jurex** [comment]
> Adjustable line thickness 
I will skip this for now
> The option to only show the intersections of lines as small crosses rather than complete lines
done
>  Rather than using a color, making gridlines a % darkness or lightness of the pixels underneath
implemented using grid opacity
