### ISSUE TITLE
Can't present images on Web Client using the external screen settings

### ISSUE THREAD

**Issue by Team-Hufflepuff** [encounterplus/encounterplus#328]
Choosing Overlay > Image and picking an image to overlay doesn't display the image in the web client, it only works on the external screen.

Clearing the image that's presented there also doesn't remove it from the web client, but choosing Overlay > None does indeed clear the image.

**Comment by jacobjohnston** [comment]
As an additional note on this issue - choosing Overlay > None does NOT seem to clear it from the External Screen (at least on the macOS build)

**Comment by jurex** [comment]
fixed
