### ISSUE TITLE
[Bugs] trouble with “pattern” assets

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#329]
I noticed patterns don't seem to honor the z level when sharing a map as a picture. They look to go below other asset types.
![image](https://user-images.githubusercontent.com/61415452/96209818-264a8280-0f36-11eb-958d-b9ade10c2461.jpeg)

Pattern sizing ignores grid size and only sizes based on pixel dimensions relative to the map.
![image](https://user-images.githubusercontent.com/61415452/96210021-9fe27080-0f36-11eb-935d-1d923b9608c3.jpeg)

**Comment by jurex** [comment]
> I noticed patterns don't seem to honor the z level when sharing a map as a picture. They look to go below other asset types.
fixed

> Pattern sizing ignores grid size and only sizes based on pixel dimensions relative to the map.
skipping this because of complexity now, please re-open as a separate ticket if necessary...
