### ISSUE TITLE
[Bug] Drawing menu cannot be closed while iPhone is landscape

### ISSUE THREAD

**Issue by Team-Hufflepuff** [encounterplus/encounterplus#332]
![image](https://user-images.githubusercontent.com/47830431/96317923-ade6ce80-0fd4-11eb-8d1e-0073d3fe5591.png)

From @mechanicalBacteria#1258:

I just tapped on the drawing tool while my iPhone (XR) was in landscape mode
If I turn it back to portrait it goes back to normal and can close the menu perfectly fine
But I have a set up where it needs be be on it’s side (so I can charge it)

**Comment by jurex** [comment]
fixed, thanks!
