### ISSUE TITLE
Video Maps Issue

### ISSUE THREAD

**Issue by the-scumbag** [encounterplus/encounterplus#334]
When I create a video map, and then move it to another module or campaign, the video portion of the map vanishes.  The walls and artifacts are intact.  If I copy it and then move it, I get the same result.  However, if I move the copy **_back_** to the original module, the video reappears.  This suggests the video is stored in the module or campaign it was originally created in, rather than the map.  

Use case: I am creating modules for each map pack from my subscription to Dynamic Dungeons, so the maps are compartmentalized and ready to import, copy, move, and remove the map module- not unlike I do with the Cze&Peku map packs.  The video being stored in the module is causing an issue, as it requires me to keep the individual video files to point the copied map to.

**Comment by jurex** [comment]
fixed, thanks for info
