### ISSUE TITLE
Feature Request- Clearer wall descriptions

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#340]
Maybe something like this?
![image](https://user-images.githubusercontent.com/61415452/97587055-fa64dd80-19c8-11eb-85cd-9908d4abd0b1.png)

**Comment by jurex** [comment]
love the idea

**Comment by jurex** [comment]
![image](https://user-images.githubusercontent.com/925257/102412707-20cfee00-3ff4-11eb-8e64-e7588bb85e0c.png)
done
