### ISSUE TITLE
Feature Request: The ability to use the import button to open an image file and create a new map

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#342]
A new user was trying to import a jpeg for use as a map, and was confused why they could import a vtt (ddvtt?) but not a jpeg ([link to discord message](https://discord.com/channels/565243968858751027/647438059226529807/772278863685615657) ). For a more unified experience, I think it would make sense to allow for importing an image, which then would open a new map with the image set as the background.

**Comment by DHCross** [comment]
That certainly makes a lot of sense, so I second the motion!

**Comment by jurex** [comment]
done
