### ISSUE TITLE
New Feature in statblocks

### ISSUE THREAD

**Issue by leoincendia** [encounterplus/encounterplus#346]
As in Tasha's Cauldron of Everything the Proficiency Bonus is now a part of the statblock.  It is located right-justified across from the CR rating. Though it could go below the CR rating and be fine there too. Sometimes it has (PB) at the end of the title, sometimes not.

**Comment by rrgeorge** [comment]
It's easy enough to calculate. Here's the formula in swift:
`let prof = 2+Int((cr < 0 ? -1 : cr > 0 ? 1 : 0)*((abs(cr-1))/4))`

**Comment by jurex** [comment]
swift version:
```swift
2 + (cr - 1).signum() * ((abs(cr - 1)) / 4)
```
