### ISSUE TITLE
Highlight distance when dragging by finger

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#347]
So the distance is shown at several times - when dragging a creature, or adding a spell etc. The issue is purely a display one - it is shown right next to the item being dragged.

Personally I find it really hard to actually see that (iPad Mini) underneath my finger. For creatures I often find myself using the external screen and trying to read it on there.

It would be nice if the distance was also shown (3x larger?) and in the top left / right corner (depending on where the finger currently is) so that it can be easily read without trying to adjust viewing angle and/or contact point of the finger.

**Comment by jurex** [comment]
yeah, the font size is based on grid size + current zoom level, so it should appear in same size regardless of the map settings (I can make it larger hovever), but the distance label position for spells are problematic during drag, I need to make it "above" the point instead of relative angle from center.

**Comment by Rycochet** [comment]
Is it not possible to duplicate it at a fixed position on screen?

**Comment by Tixuoty66** [comment]
From Shidara : 
Web Client
—Increase text size for the distance measurement when dragging tokens during combat

**Comment by jurex** [comment]
I've made some changes into path and moved distance rendering. Please re-open if still an issue on smaller devices.

> Is it not possible to duplicate it at a fixed position on screen?
I want to avoid to rendering it twice, but if this will be still an issue after the release, I'll go with it.
