### ISSUE TITLE
Grid align not working on iOS

### ISSUE THREAD

**Issue by traed** [encounterplus/encounterplus#349]
I just installed the app on iPad. It really seems like all I ever wanted except for some bugs.

Firstly, when import a map the gird doesn't show up. If I hide it and then unhide it, it works. Secondly, when I switch on the grid align feature I can't scale the tool by pulling on the dots. I can hit the "confirm" button but doing that without being able to scale the thing makes it unusable.

Also, if I bring up the grid align tool and tap anywhere else besides the confirm-button, the button disappears and I can't get rid of the tool anymore (and I still can't rescale it).

Testing this on an iPad Air (2020) running ipadOS 14.1.

**Comment by jurex** [comment]
fixed with the new context menu and button. thanks!
