### ISSUE TITLE
Imported images for a tile appearing blank

### ISSUE THREAD

**Issue by softloglongstraw** [encounterplus/encounterplus#35]
When I import an image from google drive to use as a tile it will create the tile but the image is blank until I go back in and edit the tile. I have to go back and select the same image and save again to have it appear.

**Comment by jurex** [comment]
Hmm, cannot replicate this on iOS 13. Could you send me a video @softloglongstraw or send me exact steps please? Thank you!

**Comment by softloglongstraw** [comment]
Hi Juraj,

I have a video of it but was having trouble sending it - I can try again once I get back home this evening!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jurex** [comment]
got the video, thanks!

**Comment by jurex** [comment]
found the root cause, got it fixed. it will be available in the next version
