### ISSUE TITLE
Mac: App freezes when clicking Campaigns when there are none

### ISSUE THREAD

**Issue by traed** [encounterplus/encounterplus#350]
When there are no campaigns and you click on the menu in the top right, then Campaigns, a message shows up for half a second, then disappears. After this the entire app freezes.

**Comment by jurex** [comment]
hmm, cannot replicate this anymore on the latest big sur. I'm displaying there only a simple alert, so I'm not sure what's going on. please re-test after the next release targeting big sur API. putting this on hold now
