### ISSUE TITLE
[BUG] Shortcuts disappear or are truncated on macOS

### ISSUE THREAD

**Issue by matty-dee** [encounterplus/encounterplus#353]
The shortcuts bar will leave off shortcuts when the window is resized, and not put them in the "..." window. Sometimes text will overlap, and the shortcuts arrow will also disappear. On a quit and restart, shortcuts are restored. This behavior is not always replicable, and only started for me when I moved to an M1 Mac running Big Sur.

**Comment by jurex** [comment]
fixed with a new toolbar
