### ISSUE TITLE
Bug: Scroll Lock / Fit Screen Breaks on Certain Actions

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#358]
I've seen variations of this bug on both macOS builds and iOS Builds - but they are triggered slightly differently.

To Reproduce on iPadOS:
1. Set 3D Dice to Public Display
2. AirPlay the screen
3. Present a map, and zoom in in the DM's view.
4. Choose "Fit Screen" on the External Screen display (which turns on scroll lock).
5. Roll the Dice.

When the dice roll, the player's/AirPlay view suddenly gets reset to a zoomed-in view (I think it may match the DM view).

To Reproduce on macOS:
1. Open an External Window for the Player View
2. Present a map, and zoom in in the DM's view.
3. Choose "Fit Screen" on the External Screen display (which turns on scroll lock).
4. Click the More/Ellipses icon (with Dice Roller, Campaign, etc.)

Simply open opening the More/Ellipses icon seems to cause the map to zoom in.

**Comment by jacobjohnston** [comment]
[ScrollLockBug.mov.zip](https://github.com/encounterplus/encounterplus/files/5685057/ScrollLockBug.mov.zip)

Attached is a video recording of this issue on macOS.

**Comment by jurex** [comment]
fixed. it was caused by layout change triggered on all connected scenes when presenting new controller modally from the main window on big sur. sigh
