### ISSUE TITLE
[Bug] Share map as image does not honor z ordering of assets

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#361]
When building a map in E+ i like to export it as an image, but I found the image doesn't match the map built. I pinpointed the problem being that the share only honors ordering based on when added to the map and not the manual z ordering.
![image](https://user-images.githubusercontent.com/61415452/103459090-3ae71d00-4cd2-11eb-9942-84fa6c3c42ce.jpeg)

**Comment by jurex** [comment]
fixed
