### ISSUE TITLE
Feature Request: Ability to exclude creature from XP

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#363]
I’d like to have the option to be able to exclude a monster from the encounter’s difficulty/xp calculation. Sometimes I’ll add another instance of a monster to track its lair actions, or add monsters to use for a Druid’s wildshape, or npc bystanders; and those shouldn’t be used when assigning XP or denoting the encounter’s difficulty.

**Comment by jurex** [comment]
done. now only creatures with role `hostile` are included into calculations.
