### ISSUE TITLE
Misc Mac quality of life suggestions 

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#365]
Sahwi on discord had some suggestions.  Sorry for lumping them all together.  
https://discord.com/channels/565243968858751027/634387773872275466/798589201066754048

> Juraj A few comments as a new user since I've used the application on a Mac...
>  - Having the ability to zoom in and out with the mouse wheel, and providing hotkey/shortcut support or customization for E+ would be really helpful.
>  - When interfacing with the Map vs. Compendum, streamlining what it takes to edit/delete items would be more intuitive (Map is left-click, Compendum is right click)
 > - When deleting entries in the Compendum, some sort of confirmation dialogue would be useful, as the undo feature for deleted items does not apply to the Compendum, but does apply to the map.
 > - Having a button/shortcut for easy handouts accessible on the toolbar would be nice.
 > - Presentation is kind of everything for this app... but it's all stuck behind a popup box that doesn't save when you click away. So first, you click into the popup, then you edit your content, then you click away, and it's all gone. What a hassle, from even having to open a popup at all.
 > - If an image is presented, and then you right click the toolbar to present a battlemap again, because the image acts as an overlay above the battlemap, the battlemap isn't refocused. I have to go back to the original image and unpresent it, and even then that functionality isn't consistent.
>
>Just a few notes from a new user if you're curious.
>
>It's a phenomenal app, really I'm enjoying a lot. I spent money on it though, and its implementation on macOS could be better.

**Comment by Splinter714** [comment]
This is the last feature-request ticket I have yet to organize, mostly because some of the bullets are MacOS specific. Could you help confirm if these are all still problems, or have any of these been done?

**Comment by Duseylicious** [comment]
1.)  Zoom in and out is working.  I don't know that many/any keyboard shortcuts have been implemented, however.  There may be another ticket for keyboard shortcuts.  I'd recommend shortcuts for delete (the delete button(s) do nothing right now), undo, copy, paste (on map and/or compendium), duplicate, tool selection, and find/search to start.
2.) this is done
3.) Appears not to be implemented. There is no confirmation dialogue, and undo does not undo compendium deletions.
4.) not implemented.  I believe there may be a ticket for improving handouts?
5.) I think this can be called done?  It's not entirely resolved, but the pop ups no longer dismiss when you click somewhere else, so you no longer lose your content if you didn't hit done/save. 
6.) Not implemented.  I can think of two ways to handle this, but Juraj will (as always, I suppose) need to figure out what wants to do.  One way would be making it so when you present a battle map, it clears the presented image.  Another would be simply finding an easier way to clear presented images.  Maybe this could be done in conjunction with another ticket I believe that exists about improving the handout workflow.  Just a thought.

**Comment by Splinter714** [comment]
> Having the ability to zoom in and out with the mouse wheel, and providing hotkey/shortcut support or customization for E+ would be really helpful.

zoom done, hotkeys #257 

> When interfacing with the Map vs. Compendum, streamlining what it takes to edit/delete items would be more intuitive (Map is left-click, Compendum is right click)

done

> When deleting entries in the Compendum, some sort of confirmation dialogue would be useful, as the undo feature for deleted items does not apply to the Compendum, but does apply to the map.


> Having a button/shortcut for easy handouts accessible on the toolbar would be nice.

#224 

> Presentation is kind of everything for this app... but it's all stuck behind a popup box that doesn't save when you click away. So first, you click into the popup, then you edit your content, then you click away, and it's all gone. What a hassle, from even having to open a popup at all.

less of an issue with popups no longer dismissing on click-away

> If an image is presented, and then you right click the toolbar to present a battlemap again, because the image acts as an overlay above the battlemap, the battlemap isn't refocused. I have to go back to the original image and unpresent it, and even then that functionality isn't consistent.

#482
