### ISSUE TITLE
Bug on BigSur with left click in edit mode

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#367]
Bug : with BigSur macOs, erratic behaviour in edit mode where, for no understandable reason, it is no longer possible to click on a field, as if the left-click was disconnected. One can always click Save, then Edit again and finish to complete the fields. For example, when creating new monsters, it happens at least once per monster created when filling all the fields.

**Comment by jurex** [comment]
hey @Tixuoty66 could you create me a quick video so I can try to reproduce it with the latest macOS SDK ? thanks!!

**Comment by Tixuoty66** [comment]
Hi Juraj, here is a video. I’m translating in french a monster by copy/paste different fields.

The bug starts at 2’40 :

https://drive.google.com/file/d/1Ja6XKFOu2Sjip8cTFUTkymqE9DgKrrQU/view?usp=sharing

Impossible to left click on ’Tail’.

Le 21 janvier 2021 à 15:20:37, Juraj (notifications@github.com) a écrit:

hey @Tixuoty66 could you create me a quick video so I can try to reproduce it with the latest macOS SDK ? thanks!!

**Comment by Tixuoty66** [comment]
Another one : i can scroll with mouse, i can left click on the monster name, but impossible to left click on “New Trait” or any “Trait" or “Action” to open it. If i click save, then it works again.

https://drive.google.com/file/d/19-tIYknRympIWCiWaQDzlfSlOSHudkWR/view?usp=sharing




Le 21 janvier 2021 à 17:43:37, Test (guyottest@free.fr) a écrit:

Hi Juraj, here is a video. I’m translating in french a monster by copy/paste different fields.

The bug starts at 2’40 :

https://drive.google.com/file/d/1Ja6XKFOu2Sjip8cTFUTkymqE9DgKrrQU/view?usp=sharing

Impossible to left click on ’Tail’.

Le 21 janvier 2021 à 15:20:37, Juraj (notifications@github.com) a écrit:

hey @Tixuoty66 could you create me a quick video so I can try to reproduce it with the latest macOS SDK ? thanks!!

**Comment by jurex** [comment]
awesome, thanks Tixu!

**Comment by jurex** [comment]
I did some testing with latest SDK + my app version, and everything seems working fine. It could be related to the recent big sur 11.2 update, or latest SDK. I'll close this for now now as I hope it will be fixed in the next release, but if not, please reopen and ping me back!!! thanks for videos and feedback!!
