### ISSUE TITLE
Freehand tool endpoints should honor “Snap to Grid” toggle

### ISSUE THREAD

**Issue by simonward** [encounterplus/encounterplus#37]
If the Freehand tool _endpoints_ honored the “Snap to Grid” toggle, this would make it easier to draw LoS for caverns. Currently, it’s difficult to avoid LoS “cracks” on joins between multiple paths.

Note that this request is only for _endpoints_. Other points in the path should still allow arbitrary placement.

**Comment by Splinter714** [comment]
not sure what version it was added, but this is done
