### ISSUE TITLE
Standard-sized non-scaling handles on objects

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#374]
From Shidara :
—Standard-sized non-scaling handles on objects. 
If the grid is small (<30 px), it can be very difficult to grab a handle on an object in order to resize it. Zooming in doesn’t help, because the handles scale with the zoom. Only solution is to temporarily increase the grid size until the handles can be successfully grabbed, then return to preferred smaller grid size.

**Comment by jurex** [comment]
hmm, cannot replicate it in the current dev build. handles are stop scaling after certain zoom level. closing this for now, but feel free to re-open if the issue persist
