### ISSUE TITLE
[Feature Request] Have Player Characters' Line of Sight update Fog of War

### ISSUE THREAD

**Issue by kevinsumner** [encounterplus/encounterplus#375]
I would like to have the Line of Sight cast from my player characters update Fog of War, so that as the PCs crawl the dungeon, the Fog of War gets lifted behind them, allowing them to see places they have visited in the dungeon appear on the map.

I'm not sure of the interaction between LoS and FoW at the moment, but having areas that have been uncovered in the FoW but not currently in any PC's LoS gets "dimmed" and stops showing other creatures.

**Comment by jurex** [comment]
done, thanks for your feedback!
