### ISSUE TITLE
 I can't seem to right click on the web client address and copy it in macOS.

### ISSUE THREAD

**Issue by the-scumbag** [encounterplus/encounterplus#376]
### Please allow macOS right click to display "Copy" option for the web client links in the Web Server Settings menu.  

I have "Copy Link" enabled as an option in the System Settings.

I am currently running on Mac BigSur (Version 11.1), although this functionality has never been present.

***Thanks, Juraj!***

**Comment by jurex** [comment]
will fix, thanks for the heads up...

**Comment by jurex** [comment]
all fields are selectable now
