### ISSUE TITLE
Creating a new Pack, unable to set version

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#38]
When creating a new pack (and probably when editing), the version field only accepts numbers, at the least it should accept a `.` too, and probably any characters. Adding a letter to the end gets that stripped off and just the number left.

While not everything uses SemVer, that's the least needed, but that can also optionally have suffixes. Though prescribing the format allowed would make it harder to add existing packs that use some other version string.

**Comment by jurex** [comment]
Right now it's only number, but I understand what you mean. I'll probably change it to build, and add version as a string.

**Comment by jurex** [comment]
I need to change version field type to `string` for modules and campaigns too.

**Comment by jurex** [comment]
done
