### ISSUE TITLE
Update Mac Icon to Match Big Sur App Icon Style

### ISSUE THREAD

**Issue by Puddinglord** [encounterplus/encounterplus#388]
![Screen Shot 2021-02-13 at 10 38 08 AM](https://user-images.githubusercontent.com/4474799/107854082-933c2f00-6de7-11eb-883b-f542d8ff00c7.png)

The icon for EncounterPlus feels very out of place in Big Sur. Could you update it so it's in line with the new style?

**Comment by jurex** [comment]
already did 😉

**Comment by Puddinglord** [comment]
Legend 🥇
