### ISSUE TITLE
Context Menu not working on assets and spell effects when editing maps with the Mac App

### ISSUE THREAD

**Issue by jcsparks** [encounterplus/encounterplus#396]
On the Mac App client when editing an exiting map from a campaign by either adding a graphical asset or even spell effect overlay the context menu (edit, copy, delete, hide, up, down) is inaccessible.  Assets can still be added, selected and resized but the second click on an active asset does not give the context menu.  The options are also greyed out from the Edit Menu on the task bar.  

There does seem to be a work around by loading the existing map into the battle map area, the context menu still works there and changes are persistent.  This seems to only be an issue when editing a map from a campaign or module interface via the Edit option.

**Comment by jurex** [comment]
thanks for the info. all context menu and quick menu options has been already re-worked to support latest catalyst. it will be available in the next version (4.11.0)
