### ISSUE TITLE
Add "Simplify" item to pop-up window for Wall paths

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#403]
When importing caverns and natural passageways from Dungeondraft, E+ creates a high-fidelity path to make its walls. However, this can cause a performance issue with large, complicated maps. It would be great to have a "Simplify" control in the Edit Wall pop-up that would instantly delete every other node. Clicking on it multiple times would continue to reduce the number of remaning nodes by 50%. As a bonus, it would be awesome if this could somehow detect nodes that overlap each other and automagically reduce those down to one, as I have found examples of 3-4 nodes stacked right on top of each other. 

There could be some issues introduced with this — what if one of the deleted nodes is an important one — like on a 90-degree angle? There may be a smarter way to do this — what if it just detected nodes that were overlapping or really close to others (like, within 12 pixels or something) and deleted adjacent nodes that were within this radius?

**Comment by Taliesin1** [comment]
<img width="1134" alt="Mink" src="https://user-images.githubusercontent.com/10515719/116816744-cf4e7880-ab28-11eb-9e36-b8d0111c9e05.png">

**Comment by Taliesin1** [comment]
Splinter, you relegated this to a "Maybe, someday," priority, but I think Juraj said it was relatively easy since he already had a node-reduction routine in place, but needed to implement it a little differently for this scenario. Being able to import VTT files with walls from Dungeondraft is a god-send, but they require so much pruning after import to make them usable, that it might be faster to draw your own walls. If there's any way this could be bumped up the priority ladder, all of us Dungeondraft users would really appreciate it! I'd hate for it to get forgotten amongst the 200+ issues floating around.

**Comment by jurex** [comment]
done

**Comment by Tixuoty66** [comment]
Oh amazing !

**Comment by Taliesin1** [comment]
My prayers have been answered by the Juraj! Thanks so much!
