### ISSUE TITLE
[Bug] Enemy light source seen as part of "shared visibility"

### ISSUE THREAD

**Issue by Splinter714** [encounterplus/encounterplus#410]
Light sources on enemy tokens currently behave as part of the player party with respect to visibility sharing settings. Both of the below screen shots were taken in player mode. Two cases, both problematic.

![IMG_0113](https://user-images.githubusercontent.com/65372425/114261994-511c0d80-9992-11eb-9566-ecdf67aed1cd.jpg)
![IMG_0110](https://user-images.githubusercontent.com/65372425/114261995-51b4a400-9992-11eb-9940-949929d8eeee.jpg)

**Comment by Splinter714** [comment]
To clarify, I'm hoping that once this is fixed, the vision for "friendly" NPC tokens would still be shared with the party depending on the shared visibility settings.

**Comment by jurex** [comment]
I've added a fix for this, but you need to move token to see the change between friendly and enemy toggle. I need to write a better vision invalidation for this, but I'm short of time now.
