### ISSUE TITLE
Setting creature to "Friendly" causes web server black screen

### ISSUE THREAD

**Issue by JedanL46** [encounterplus/encounterplus#411]
Hey there, during the session tonight one of my players summoned an Air Elemental, which is fairly common. I went ahead and spawned it in and then set it to friendly as normal. After that though the entire screen the players could see on the web server went black and it could not be recovered, we tested it a bunch and found setting a creature to friendly is the source of the problem.

**Device:** 2020 iPad Pro

**Steps to replicate:**

1. Create new webserver and display a map
2. Login to the web server with browser
3. Add a creature in to the encounter
4. Set the creature to "Friendly", you may notice it does not become visible on the battle map for the players
5. Refresh the web page in browser and the entire screen will be black
6. Try setting the creature to hostile or neutral and refreshing, the page should restore
7. Attempt step 4 again to confirm and refresh page

This seems to only occur no matter if LOS is active or not.

Hope this helps,
Jedan

**Comment by jurex** [comment]
I've fixed blackscreen today with web client hotfix

**Comment by JedanL46** [comment]
I just loaded up my encounter and was able to confirm it was fixed in my case, cheers!
