### ISSUE TITLE
[Bug] in Token Edit menu, can't toggle "not present" combat toggle more than once. 

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#414]
If I right click - edit a token, then under COMBAT TRACKER toggle the "not present" option, it works.  I toggle it again, and it works correctly again, remove the token from combat.  If I try immediately again, it will no longer add them to combat.  

It works again if I leave the token edit window and open it up again.

**Comment by jurex** [comment]
Hmm, I can't reproduce it properly on big sur. Will try again on Catalina later. I've fixed combat tracker toggle when accesing token from the initiative tracker creature, because you cannot remove it from combat from there. it will break the navigation.

**Comment by Duseylicious** [comment]
This is working for me now 😅 We can close and I'll come back if I see it again and can reproduce it.
