### ISSUE TITLE
Token quick-menu (double tap) button order disrupted when token leaving/entering combat

### ISSUE THREAD

**Issue by Splinter714** [encounterplus/encounterplus#419]
In the token quick menu accessed by double tapping a token, the positions of enter/leave combat and hide/unhide are inconsistent between the enter/leave combat states. In one state, the buttons are in positions 2 and 3 from the left. In the other state, the buttons are in positions 4 and 5 from the left. Ideally this would function similarly to the hide/unhide button in the same menu which keeps those two buttons in the same position in both states.

I understand this is not a bug per se, more of an effect of which options are shown in the quick menu, but it would be much better to keep the toggle off/on type buttons in the same position between states.

![InkedIMG_0106_LI](https://user-images.githubusercontent.com/65372425/114261494-be7a6f00-998f-11eb-9643-1ae6634ebf0d.jpg)
![InkedIMG_0108_LI](https://user-images.githubusercontent.com/65372425/114261496-bfab9c00-998f-11eb-8f1b-ad0c90290e94.jpg)

Example of how it works flawlessly for hide/unhide:
![InkedIMG_0107_LI](https://user-images.githubusercontent.com/65372425/114261495-bf130580-998f-11eb-939e-3ac3ca0cd3f2.jpg)

**Comment by jurex** [comment]
moved damage icon and condition icon after edit icon
![image](https://user-images.githubusercontent.com/925257/117498557-3ed5c500-af7a-11eb-91c9-036ab1d92f08.png)
