### ISSUE TITLE
Token vision limit error

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#424]
When setting a map vision limit (ie 100), a token with darkvision will not see further his darkvision limit (ie 60), even if it’s full daylight. His vision should be 100.

**Comment by jurex** [comment]
so I was checking the code, and the vision limit automatically enable daylight 0, so it takes max radius either from light/dark vision and vision limit. I will leave it as it is now because it's intended, but can revisit later if necessary.
