### ISSUE TITLE
When editing monster name from initiative pane, token label on map does not update

### ISSUE THREAD

**Issue by mattd** [encounterplus/encounterplus#426]
Using version 4.11.0

Steps to reproduce:

1. Put any monster on a map via "Insert Creatures"
2. Edit the monster from the initiative pane by swiping left and tapping the edit button
3. Change monsters name to Bob with token label B
4. Tap Save
5. Note that the token label is changed to B in the initiative pane but not on the map

**Comment by jurex** [comment]
fixed, thanks for report!
