### ISSUE TITLE
E+ Crash on Mac

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#427]
I got an E+ crash, never got this before. I was editing a compendium monster. Here is the crash report.
[EncounterPlus_2021-04-10-113536_iMac-Jean-Marc.txt](https://github.com/encounterplus/encounterplus/files/6291226/EncounterPlus_2021-04-10-113536_iMac-Jean-Marc.txt)

**Comment by jurex** [comment]
I think this is related to the #425 will close for now, but please reopen if the issue surface again after the next update
