### ISSUE TITLE
Friendly Creatures should be included in awarding experience

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#429]
When awarding XP, creatures marked as friendly (like NPCs), should be included in the options for distribution.

**Comment by Rycochet** [comment]
Maybe non-Beast type friendly creatures, so pets wouldn't get a share, but Allies would ?

**Comment by jurex** [comment]
done. I've reverted the npc section in award experience screen, and changed it to friendly non-players
