### ISSUE TITLE
Inconsistent token assignment issues when editing a monster from the initiative pane

### ISSUE THREAD

**Issue by mattd** [encounterplus/encounterplus#439]
I'm on 4.11.0 (2282)

When editing a monster from the initiative pane and assigning a token from an existing pack, behavior is inconsistent. Sometimes the token on the map is replaced by a large light gray X. Sometimes the token on the initiative pane updates but the map stays as-is. Sometimes the token on the map updates successfully but the initiative pane does not. I have not yet gotten both the map and the initiative pane to update successfully at the same time.

This does _not_ happen when editing the monster from a long press on the map token. When editing there, both the map and initiative pane update as expected.

**Comment by jurex** [comment]
fixed, thanks for report!
