### ISSUE TITLE
Web Client: Allow port other than 8080

### ISSUE THREAD

**Issue by microbuilder** [encounterplus/encounterplus#440]
In order to use the web client, you must open port 8080 on the router (https://help.encounter.plus/web-client-faq) ... however, some routers restrict access to this port or reserve it for internal use. Allowing users to indicate which port to use would allow the web client to work on any router.

**Comment by jurex** [comment]
it's already implemented. Check app settings > Remote Play > Settings > Port

**Comment by microbuilder** [comment]
Thanks, I'd suggest updating the FAQ to highlight this.
