### ISSUE TITLE
Extra Comma and Space

### ISSUE THREAD

**Issue by leoincendia** [encounterplus/encounterplus#448]
Small biscuits issue, but with the new stat block in Tasha's and Candlekeep not including alignments they also remove the comma that is between the creature type and its alignment. Currently, the system can have the alignment blank but still leaves the comma in place. In a similar fashion, there is a space placed between the Title and Text of traits, actions, etc. If the title is blank there is still a lingering space that offsets the text. This is most often seen in the Legendary actions where the first line explains how many legendary actions a creature has, but has no title.

**Comment by jacobjohnston** [comment]
Confirmed: 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1703107/115260686-d6689600-a0e7-11eb-9b8c-3d6cd58c50dd.png">

**Comment by jurex** [comment]
fixed with support for empty alignment and empty action/trait name
