### ISSUE TITLE
Subviews from "External Screen" have wrong color "<Back" button

### ISSUE THREAD

**Issue by simonward** [encounterplus/encounterplus#45]
Specifically: Overlay: Type, Battle Map: Presenting, In-Combat Theme: Initiative Style.
![IMG_0458](https://user-images.githubusercontent.com/1904698/74790758-6f461c00-526d-11ea-9288-ab0fd83c179d.png)
![IMG_0459](https://user-images.githubusercontent.com/1904698/74790761-710fdf80-526d-11ea-90f6-57cee93dd63d.png)
![IMG_0460](https://user-images.githubusercontent.com/1904698/74790763-71a87600-526d-11ea-800f-3fe03f123667.png)

**Comment by jurex** [comment]
fixed
