### ISSUE TITLE
Feature Request: Include Multiplication and Division in die roll commands

### ISSUE THREAD

**Issue by the-scumbag** [encounterplus/encounterplus#451]
I'd like to see the ability to multiply or divide die roll results.  For example: Long-term Madness lasts 1d10x10 hours.  Adding the link to roll that number is not currently possible. Adding a '*' **_adds_** the multiplier to the die roll.

**Comment by rrgeorge** [comment]
Using `/` also adds instead of divides.
Also, some special notation needs to be established in order to use `/` in a `/roll` url.

**Comment by jurex** [comment]
done, but the order of operations (or operator precedence) is not implemented properly yet. Need to revisit dice expressions and also add support for parentheses in future.  

currently supported math operations:
```javascript
"+", "-", "*", "/", "x", "×", "÷"
```

**Comment by rrgeorge** [comment]
Looks like I’m going to need to update my dice regex for EncounterLog
