### ISSUE TITLE
Zooming using the scroll wheel should be centered on mouse position

### ISSUE THREAD

**Issue by giovannipiller** [encounterplus/encounterplus#452]
Right now, zooming using a mouse scroll wheel will zoom to/from the map's center coordinates.
I feel like it would be so much better if it used mouse's coordinates instead.

For example: right now, if you want to zoom on the top right corner of the map, you have to use the scroll wheel to zoom first, then click and drag the map to pan to the top-right.

**Comment by jurex** [comment]
done
