### ISSUE TITLE
When first turning on Fog of War, it is creating only "half" opacity fog.

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#454]
When turning on Fog of War for the first time on a newly created map, it's only creating half-darkness - presumably because of an uninitialized fog layer/texture. The "reset" button works fine. I assume this only happens on the same video cards that had the similar issue with Reset during beta.

**Comment by jurex** [comment]
I've added additional check for an empty image in the fog texture initializer, so it should be working now. However, I cannot properly validate it (no external gpu on my mac). Please re-open if the issue persist.
