### ISSUE TITLE
Fog of War Regions do not show up when editing a map unless Fog of War is toggled off then on again.

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#455]
To Reproduce:
1.) Create a map.
2.) Turn on Fog of War
3.) Add Fog of War regions to map.
4.) Save and Close Map
5.) Edit Map Again

Observe that Fog of War regions are no longer visible when editing the map. To get them to show up, toggle the FoW option off then on again. See attached video.

https://user-images.githubusercontent.com/1703107/115119772-f9b40980-9f5e-11eb-8b9c-ac643a1342f1.mov

**Comment by jacobjohnston** [comment]
I'm not sure if this happens on all systems. If not, it may be related to issue #454

**Comment by jurex** [comment]
Fixed with the unified map loading function
