### ISSUE TITLE
Monsters Stats display bug  on Mac

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#456]
Strange bug with monsters stats (only on Mac not on ipad). Seems to be only a display issue (cause i can click on Str roll for ie and it rolls a d20+4).
![Capture_decran_2021-04-18_a_20 39 14](https://user-images.githubusercontent.com/68757286/115163329-cda49f80-a0a8-11eb-8aca-6e58a6f44722.jpg)

Jacobj comment : Yeah, looks like fallout from the font size increase on macOS. I can reproduce that. Note that if you change the value to any single digit, it's fine. I think the modifier is getting wrapped to the next line, which is clipped

**Comment by jurex** [comment]
Fixed with removed clipping and wider sidebar on catalyst
