### ISSUE TITLE
Impossible to display images to players (small white square invisible) on Mac

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#458]
### What went wrong?
- No image display possible to players cause the small white square top left allowing to share the image is not visible

### What steps can we follow to reproduce the issue?
- Try to share an image from a page or a compendium monster for ie, opened in the main screen. If it's done from the library window, it works fine.
- Juraj comment : there is also resize issue on mac when showing image in fullscreen, that library I'm using for image previews is pretty old and cannot handle it properly. I need to roll my own solution for images soon. There needs to be shadow or circle with transparent bg.

### What software versions are you currently using?
- EncounterPlus 4.11.1 / MacOS 11.2.3

### Any screenshots, videos, logs, or error messages?
![Capture_decran_2021-04-12_a_00 02 38](https://user-images.githubusercontent.com/68757286/115199594-aaeba880-a0f3-11eb-940e-742c084778af.jpg)

### Any other comments?
- very annoying, i almost use this every game session to show players objects they find or characters they meet (scrolls, books, NPC pictures...)

**Comment by jacobjohnston** [comment]
Not a solution to this problem at all, but to work around this until the view gets changed I often use some of these tactics:
- You can always swipe up to dismiss the view if you're having issues finding the close button
- You can invoke images through the "Overlay" presentation menu (though not ones embedded in pages, as far as I know).
- You can stretch/resize the DM view a bit on macOS to reveal the Share button

**Comment by Tixuoty66** [comment]
Swipe is ok to close. But as most of images are embedded in pages, can't use overlay. Tried to stretch/resize the DM view, but it doesn't change anything. So unable to share images at the moment.

https://user-images.githubusercontent.com/68757286/115280295-12334800-a148-11eb-8428-4763255cd52c.mp4

**Comment by rrgeorge** [comment]
It seems the problem is that the buttons are under the toolbar. Big Sur appears to have a larger toolbar that covers the buttons completely. However on Catalina, you can the issue since the buttons are only partially covered.  
![C41A214D-397B-4D4A-ABA8-6FE8E4427A47](https://user-images.githubusercontent.com/8526392/115286265-bba41a80-a103-11eb-8818-31e6b9c98c6a.jpeg)

**Comment by Tixuoty66** [comment]
It’s more a bug than a feature request.
