### ISSUE TITLE
Keyboard Blocks Map Settings Panel on iPhone

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#459]
### What went wrong?
- When trying to edit text fields on the Map Settings panel such as `Scale` or `Units` the keypad covers the entire panel

### What were you expecting to happen?
- The panel should shift up above the keyboard so it is still visible

### What steps can we follow to reproduce the issue?
1. Tap the map settings gear
2. Tap in a text field

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14.4.2

### Any screenshots, videos, logs, or error messages?

https://user-images.githubusercontent.com/8526392/115276750-4aab3580-a0f8-11eb-9fb5-e0d6eeca8fc9.mov

### Any other comments?
-

**Comment by jurex** [comment]
Fixed in #460
