### ISSUE TITLE
Change "Hidden" creatures to also hide from remote initiative list

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#46]
_n64billy_: Requesting that creatures marked as ‘Hidden’ in the initiaive list, also stay hidden from the Initiative List displayed to players

_Team-Hufflepuff_: Actually, marking creatures as hidden like that is how it works in Fantasy Grounds too
_Team-Hufflepuff_: It hides them from the players view on the map and the list
_Team-Hufflepuff_: R20 as well, I think

**Comment by Rycochet** [comment]
Potential options related to this:

`Show Hidden Creatures in Initiative List` (*n64billy*)

`Show Enemies in Initiative List`
`Show Allies in Initiative List`
`Show Companions in Initiative List`
`Show Familiars in Initiative List`

---

Basically allow each type to be hidden individually, either via a sub-menu, or an option on the Settings page.

Use case for them is that some of these might not want to take part in combat, or their initiative might want to be hidden and just the Players' shown.

**Comment by jurex** [comment]
initiative list in the external screen (airplay) now supports hidden creatures. it's possible to enter/leave combat and quickly hide/unhide tokens with the new token workflow, so I don't wont to complicate it more with additional options. we can revisit later if necessary. closing now
