### ISSUE TITLE
Map Settings Panel disappears when rotating iPhone

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#460]
### What went wrong?
- Map Settings Panel disappears off screen when rotating iPhone from Portrait to landscape
- Right side of screen (where panel was covering in portrait orientation) does not respond to touches

### What were you expecting to happen?
- The Map Settings panel should resize and remain visible 

### What steps can we follow to reproduce the issue?
1. Open map settings when iPhone is in portrait orientation 
2. Rotate phone to landscape orientation 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 14.4.2

### Any screenshots, videos, logs, or error messages?

https://user-images.githubusercontent.com/8526392/115277335-02404780-a0f9-11eb-8f68-b659044fe071.mov

### Any other comments?
-

**Comment by jurex** [comment]
Fixed by forcing popover presentation even on iphone
