### ISSUE TITLE
Copying a light on light layer doesn't keep original light settings

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#462]
### What went wrong? ### What were you expecting to happen?
- when copying a light, you expect the same settings for the copied light 

### What software versions are you currently using?
- EncounterPlus 4.11.1
- Operating System macOS 11.2.3

### Any screenshots, videos, logs, or error messages?

https://user-images.githubusercontent.com/68757286/115388270-f8dbdb80-a1db-11eb-8fdb-9d007718f9bd.mp4

**Comment by jurex** [comment]
Fixed. There were multiple rounding issues and snap to grid was not working properly either. Thanks for report!
