### ISSUE TITLE
On light layer, when selecting 'player view', the light icon is still visible

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#463]
Really not a priority, but...

### What went wrong ? ### What were you expecting to happen ?
- On light layer, when selecting 'player view', the light icon shouldn't be visible

### What software versions are you currently using?
- EncounterPlus 4.11.1
- Operating System macOS 11.2.3

### Any screenshots, videos, logs, or error messages?

https://user-images.githubusercontent.com/68757286/115390987-368e3380-a1df-11eb-8d61-828c7e034beb.mp4

**Comment by jurex** [comment]
fixed with switching back to the token layer
