### ISSUE TITLE
Area effect sizing error

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#464]
### What went wrong?
- Adding an area effect by double-click on a map & entering a dimension (radius / units) doesn't result with the right size. Seems it's in feet and doesn't take into account the map scale unit given.

### What were you expecting to happen?
- An area size that respects map scale unit

### What software versions are you currently using?
- EncounterPlus 4.11.1
- Operating System macOS

**Comment by Tixuoty66** [comment]
![E83507A9-528E-4C6F-BF3B-B2FD646A5A08](https://user-images.githubusercontent.com/68757286/115765112-a4388c00-a3a6-11eb-8ba3-eb71b74c1b92.jpeg)

**Comment by Tixuoty66** [comment]
On the printscreen : should be a 3m circle, and on the circle drawn on the map is 0.9 m

**Comment by jurex** [comment]
fixed
