### ISSUE TITLE
Crash When Adding Background Image to Map

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#469]
### What went wrong?
EncountPlus crashed when adding a background image to a new map. Upon relaunching E+, the background image appears to have been successfully added.

### What were you expecting to happen?
E+ not to crash.

### What steps can we follow to reproduce the issue?
Not reproducible, but crash log is attached.

### What software versions are you currently using?
- EncounterPlus: 4.11.1
- Operating System:  macOS 11.2.3

### Any screenshots, videos, logs, or error messages?
See attached crash log
[EncounterPlusCrash.txt](https://github.com/encounterplus/encounterplus/files/6372524/EncounterPlusCrash.txt)

**Comment by jurex** [comment]
it crashed due to the access to already deleted object. did more safety checks inside content controller, should be better now.
