### ISSUE TITLE
Initiative tracker doesn’t respect Combat load mode

### ISSUE THREAD

**Issue by joelohrum** [encounterplus/encounterplus#470]
### What went wrong?
- When creatures are added via the initiative tracker hamburger menu, tokens are loaded to the map even when Load Mode is set to Combat. 

### What were you expecting to happen?
- In that setting, only an initiative entry should be added, not a map token

### What steps can we follow to reproduce the issue?
1. Set Load Mode to Combat
2. Using the hamburger menu in the initiative tracker, add a creature PC.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14.6 beta

### Any screenshots, videos, logs, or error messages?
Video: https://photos.app.goo.gl/JEchkHxeV8MM1u6o7

**Comment by Splinter714** [comment]
possibly related to #428

**Comment by jurex** [comment]
quite opposite that #428 I will leave it as is for now.
