### ISSUE TITLE
“Co-DM” or allow a player to control monsters in the web client.

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#481]
### What would you like to see added to EncounterPlus?
- I would love to have another player or a co-dm be able to control monster movement from the web client. 
-Two examples of using this.  Example 1, My son has recently decide he likes to co-dm more than playing.  I’d love for one of us to run e+ like normal, and the other to be able to run things from the web client.  (Long term it’d be _amazing_ for him to roll for monsters from the web client as well.) he sits next to me on a 100% local game.
-  Example 2, I have a player who I’d love to be able to control monsters (and frankly ANY token) from the web client, because I am using a tv table for maps and using physical minis on the table. However, I have 2 players who are remote, and will use the web client. One of my local players has volunteered to mirror everyone’s movements with the physical minis, on the web client, so the remote players can see what’s going on

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14 and Mac Catalina

**Comment by rrgeorge** [comment]
I like really like this idea, but I think it’s important that player authentication exists as a prerequisite.

**Comment by jurex** [comment]
completed with `?interactions=all` url parameter
