### ISSUE TITLE
Clearing token label does not work if combat tracker label is cleared

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#485]
### What went wrong?
- If you clear the combat tracker label, then the token displays with an empty dot, rather than no label. 

### What were you expecting to happen?
- For the label to disappear.
- If you only clear the label on the token it works as expected.

### What steps can we follow to reproduce the issue?
1. Add a creature to both combat and map
2. Edit the creature on in the combat tracker
3. Remove the label
4. Save

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 14.5

### Any screenshots, videos, logs, or error messages?
Label cleared on both combat entry and token:
![A65A4686-8DDA-4C65-9F0A-42038456B85D](https://user-images.githubusercontent.com/8526392/116767804-5e537780-a9e7-11eb-942c-86ffb271eb58.jpeg)

Label cleared on only the token:
![27F6AFEE-EC0F-4325-99C0-1BB97BF0B4FE](https://user-images.githubusercontent.com/8526392/116767798-57c50000-a9e7-11eb-9742-e9447fcc208c.jpeg)

### Any other comments?
-

**Comment by Tixuoty66** [comment]
This is indeed the case for monsters, not for players.
![Capture d’écran 2021-05-01 à 07 24 13](https://user-images.githubusercontent.com/68757286/116772328-93df7b80-aa4e-11eb-8f85-66b626cca1f8.jpg)

**Comment by Taliesin1** [comment]
Confirmed. Just encountered this myself.
