### ISSUE TITLE
Unable to resize the window when editing a page (on Mac)

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#486]
### What went wrong?
- When editing a page on Mac, the default size of the window is ridiculously small and it's now impossible to resize it, nor to move it. It becomes difficult to create a whole module in this way, without being able to resize the editing page. It seems to me that this was possible in the previous E+ release.

### What were you expecting to happen?
- classic window options: resizable, movable

### What steps can we follow to reproduce the issue?
1. Edit a page (on Mac)

### What software versions are you currently using?
- EncounterPlus 4.11.1
- Operating System macOS 11.3

### Any screenshots, videos, logs, or error messages?

![Capture d’écran 2021-05-01 à 07 19 55](https://user-images.githubusercontent.com/68757286/116772462-8d9dcf00-aa4f-11eb-9de3-59e57ac8fafb.jpg)

**Comment by jurex** [comment]
Resizing modal views is not possible right now when using Catalyst (it should be imho), so I've changed the presentation to fullscreen for pages.
