### ISSUE TITLE
Resize window for pages when in view-only mode

### ISSUE THREAD

**Issue by bane73** [encounterplus/encounterplus#487]
### What would you like to see added to EncounterPlus?
- Somewhat similar to issue #486 except that was about resizing a page while editing it whereas this one is about resizing it while reading it (in which case the page is EVEN SMALLER than the one in #486 
- Additionally, the standard text is really small (though that's probably mostly my poor eyes' fault and I having glasses arriving in a few weeks so if you disagree the font should be any larger I'm totally OK with that; just figured I'd mention it)

### What software versions are you currently using?
- EncounterPlus 4.11.1 (2308)
- macOS 10.15.7

This screenshot is showing that the read-only view of a page is roughly the same size as the combat tracker and the About-info widgets (and this view can't be resized, though I don't know how I can show that in a screenshot). Also, the standard text is really small 
![image](https://user-images.githubusercontent.com/1545720/116796176-ce213b00-aa97-11eb-9287-5808a48b836d.png)

**Comment by jurex** [comment]
All floating windows (initiative tracker included) can be resized by dragging bottom-right corer. There is no visual indicator (can't find a nice unobtrusive UX for it), but it just works.

**Comment by bane73** [comment]
Woah, that's awesome! I could only get it to work in the lower right-hand corner but I'll take it. Thanks so much!
PS: maybe a "tips and tricks" when the app first starts, with things like this?
