### ISSUE TITLE
Allow background music to keep playing while a video map is in use (iOS).

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#504]
### What would you like to see added to EncounterPlus?
- Right now, if I'm playing music, and I load a video map, the music stops.  I'd like for it continue, and to ignore the music / audio on the video map.  

Related to https://github.com/encounterplus/encounterplus/issues/311

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14.  (issue does not appear on mac)

**Comment by jurex** [comment]
fixed in #344
