### ISSUE TITLE
Presentation of WebP images doesnt work.

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#507]
### What went wrong?
- Clicking on a WebP image in a page jumps out to Safari to attempt to load the image from https://encounter.plus....

### What were you expecting to happen?
- Should have loaded the image full screen to give the option to present it

### What steps can we follow to reproduce the issue?
1. Add a WebP image to a page in a module with an `<img>` tag
2. Load the page in EncounterPlus
3. Click the image

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 14.5

### Any screenshots, videos, logs, or error messages?
None

### Any other comments?
-

**Comment by jurex** [comment]
related to #465, fixed for gif images as well..
