### ISSUE TITLE
Feature Request: dice rolling from pages

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#51]
It would be awesome if the same dice rolling logic from stat blocks and spells worked in pages. This would be useful for traps, environmental hazards, etc.

**Comment by jurex** [comment]
done

**Comment by jurex** [comment]
dice rolls can be created by html anchor tags like this:

`<a href="/roll" title="optional title">2d20kh1 + 5</a>`

or

`<a href="/roll/2d20">Some text</a>`

don't forget to urlencode when using direct href attribute.
