### ISSUE TITLE
Quick Actions for tokens reference link when there’s no reference

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#511]
### What went wrong?
- Quick actions on tokens displays a button for the reference when there is no reference. 
- The button gives no response when tapped

### What were you expecting to happen?
- The button should be hidden when there is no reference

### What steps can we follow to reproduce the issue?
1. Add a token without a reference
2. Tap on it

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14.5.1

### Any screenshots, videos, logs, or error messages?
![600FD1A8-7A32-43B5-A597-35A3AACA2265](https://user-images.githubusercontent.com/8526392/118000993-2a3b5900-b2fb-11eb-94f1-4fddeda8b005.jpeg)

### Any other comments?
-

**Comment by jurex** [comment]
fixed
