### ISSUE TITLE
"Initiative mode" setting not taken into account when monsters added to combat & initiative auto rolled

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#513]
### What went wrong?
- when entering monsters in combat, initiative is auto rolled but doesn't respect the 'initiative mode' settings : "Group" setting for example is broken.

### What were you expecting to happen?
- consider 'initiative mode' settings
- 

### What software versions are you currently using?
- EncounterPlus 4.11.2

**Comment by jurex** [comment]
fixed
