### ISSUE TITLE
On Mac, long press on load button does give options

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#515]
### What went wrong?
-  On Mac, neither click and hold nor right click brings up these options.  (I'm using a magic mouse.) 

### What were you expecting to happen?
- On iOS, when you hold the load button, you get 3 options to load into combat & map, just combat, or just map.  I was expecting a right click to bring up the options.

### What steps can we follow to reproduce the issue?
1. Happens every time.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.2):
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): macOS 10.15.7 

### Any other comments?
-

**Comment by jurex** [comment]
Right click on load icon is supported from Big Sur (macOS 11.0 + )
