### ISSUE TITLE
Opening Wrong Map

### ISSUE THREAD

**Issue by BeauNouvelle** [encounterplus/encounterplus#518]
### What went wrong?
- Wrong map is being shown when making it active. In particular, the previously opened map shows instead.

### What steps can we follow to reproduce the issue?
Not too sure, it doesn't happen every time, but this is what I did:
 1. Open a map in the main view (not editor).
 2. Close map. Open another.
 3. When opening the second map, the first is shown instead. The title in the window reflects the new map name, but the map itself is the previous one.
 4. The only way to fix this is to open both maps. Switching between tabs then shows correct maps. Upon closing the previous map, the new one stays as it should.

### What software versions are you currently using?
- 4.11.2
- macOS 11.4 M1 MacBook Air.

### Other Comments
I'm not sure what else I can try. But I can reproduce this quite often.
Restarting the app seems to fix this for a short while.

I'm using animated maps. mp4s. With audio.

Perhaps this previous map is being held in memory.
When closing one of these animated maps, the sound continues to play.

**Comment by jurex** [comment]
can't replicate it, but I've fixed some issues when unloading animated maps, hope it will help. If not, please re-open
