### ISSUE TITLE
Edit Image "Cancel" does not cancel and dismiss editor

### ISSUE THREAD

**Issue by simonward** [encounterplus/encounterplus#52]
Edit Image "Cancel" does not cancel and dismiss editor.

Steps:
1) Set an background image in Map Settings
2) Tap image and select "Edit Image"
3) Make an image edit.
3) Tap the "Cancel" button.

Result:
The edit isn't discarded, and the editor isn't dismissed.

![iPad_Cancel](https://user-images.githubusercontent.com/1904698/75288357-11678600-57d1-11ea-84bb-b7a3b75a6925.png)
![iPhone_Cancel](https://user-images.githubusercontent.com/1904698/75288359-12001c80-57d1-11ea-8ceb-2fa9c5acc0c1.png)

**Comment by jurex** [comment]
fixed, thanks @simonward
