### ISSUE TITLE
Light source on creature token remains lit even when hidden

### ISSUE THREAD

**Issue by matty-dee** [encounterplus/encounterplus#532]
When adding a light source to a creature (such as Will o' wisp) the light remains even if the creature is hidden, or out of combat.

 If this behavior is intended, maybe make an easily accessible toggle for light source on the pop-up menu so we can hide these creatures quickly. Thank you!

**Comment by Splinter714** [comment]
Would LOVE to see a quick toggle for light source. I think ideally it's still possible to have a hidden creature with a light source visible, but it may be a bit of an edge case.

**Comment by jurex** [comment]
I've added a new menu entry "enable/disable light" to the token and tile context menu. It's easier than handling hidden state in vision renderer.

**Comment by Splinter714** [comment]
@jurex does that mean #420 could be closed as well?
