### ISSUE TITLE
Compendium image search and outside links don’t work

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#533]
### What went wrong?
- Long pressing on a monster’s name for an image search no longer works. It now gives a “content not found” message
- Outside web links in compendium entries no longer open safari, instead you get the same “content not found” message

### What were you expecting to happen?
- For the link to open in Safari

### What steps can we follow to reproduce the issue?
1. Open a compendium entry and long press on the monster’s name
Or
2. Open a compendium entry that has a link in it, and tap on the link. (For example, all D&D Beyond imported characters have a link at the end to the sheet in D&D Beyond)

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 14.6

### Any screenshots, videos, logs, or error messages?

https://discord.com/channels/565243968858751027/647438059226529807/847457710336245770

### Any other comments?
- This like related to the fixes for #220 and/or #285

**Comment by jurex** [comment]
fixed
