### ISSUE TITLE
Add modify PC token health to API

### ISSUE THREAD

**Issue by Puddinglord** [encounterplus/encounterplus#545]
### What would you like to see added to EncounterPlus?
- Currently, you can modify a player's Initiative using external rolls. I propose adding an API route that would allow you to specify the tokens name/id and pass it either a positive or negative integer thus healing or damaging the characters token. This would allow extensions and 3rd party applications to read DDBs health modifications and then apply them in Encounter+.

### What software versions are you currently using?
- EncounterPlus (4.11.2)
- Operating System (iPadOS 15.0)

**Comment by Puddinglord** [comment]
> Chrome has an extension that does this on the DDB campaign page https://chrome.google.com/webstore/detail/dd-beyond-campaign-dm-scr/oiajbaepngjfcgimlkaedfkdjkklkfhh

Indeed this has that. I am looking for a more integrated solution though given that Initiative rolls are already handled by E+ when rolling on DDB with EncounterLog.

**Comment by rrgeorge** [comment]
There will also be a similar overview EncounterLog, and if this feature can be implemented, EncounterLog could push updates to E+.

**Comment by jurex** [comment]
done.

there is a new API in the web sever `PUT`/`PATCH` `/api/tokens/{id}` which you can use to manipulate token fields. Also a new web socket event named `updateModel` for token data:

```json
{
    "name": "updateModel",
    "model": "token",
    "data": {
        "id": "D52625FB-C491-41B2-B70F-C6981E80775A",
        "health": 5,
        "path": [100,150,200,250]
    }
}
```
