### ISSUE TITLE
Add Webpage as Content

### ISSUE THREAD

**Issue by timbomckay** [encounterplus/encounterplus#546]
### What would you like to see added to EncounterPlus?

Something that might be helpful while waiting for other features to be included would be an ability to provide new content as a reference to a website. This could be helpful for things such as a Trello board for inventory, D&D Beyond character profile, Dropbox file, Google Docs embed, markdown notes, external images, etc, allowing the DM to remain in Encounter Plus instead of opening their browser.

![image](https://user-images.githubusercontent.com/784904/123187689-9e276000-d468-11eb-9984-1638c2b8bdbd.png)

I'm not sure if this poses any security risks as I know this is a feature Swift is capable of, but might require `https` if needed.

### What software versions are you currently using?
- EncounterPlus: `4.11.1`
- Operating System: `macOS 11.3.1`

**Comment by jurex** [comment]
done using new **reference** content type

**Comment by timbomckay** [comment]
Awesome. Glad to hear it.

Will this be handling the font-sizes and scaling the same way that the markers currently do?

Link to Discord thread: https://discord.com/channels/565243968858751027/582622828201902093/896481467327217724

> I've been playing around with the web preview reference and wondering if there's a zoom level set on it? I ran a script to get initial width & font-size and it says it's 350px wide and a standard 16px font-size, but it looks smaller than when I scale my browser down to the same. Any insight on this?
>
>  Comparison: 
> 
> ![image](https://user-images.githubusercontent.com/784904/147829893-ae8ce871-70b0-4339-bc1e-e0319659fd29.png)
