### ISSUE TITLE
“Flat TV” / Table Tv improvements - grid increment panning 

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#547]
### What would you like to see added to EncounterPlus?

My biggest issues I have in this regard is getting the grid to 1 inch quickly, stay there, and pan in a way that I don’t have to fiddle with it so much to line it back up with minis if I show something else then come back.

Some random thoughts on handling it.  
Adding a zoom lock that still allows panning. 
Adding the ability to type in your tv size / dimensions and have it automatically make the grid 1-inch (or any arbitrary size.)
Being able to set a static external zoom level that the map always remembers and defaults to / can be reset to
Allowing an option to pan by grid-increments i.e. 1-inch increments (grid-snap panning?  Maybe keyboard arrows could pan the external display 1 inch.  Or WASD could.)

Related tickets: 
https://github.com/encounterplus/encounterplus/issues/26
https://github.com/encounterplus/encounterplus/issues/27
https://github.com/encounterplus/encounterplus/issues/28

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iPadOS & Mac

**Comment by jurex** [comment]
So the new camera panning with "camera move" and "camera point" actions is quite good now. It respects grid snapping, so you can technically move by specific grid units and back if you want. Closing for now.
