### ISSUE TITLE
Add quick Create Map button to image viewer

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#549]
### What would you like to see added to EncounterPlus?
- When viewing an image full screen, I'd like to see an additional button that would allow you to instantly create a new map from that image

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iPadOS 15

**Comment by jurex** [comment]
Done. iOS 14+ only

![image](https://user-images.githubusercontent.com/925257/130074583-a86a831c-5448-4557-9e26-e579c50df6d2.png)
