### ISSUE TITLE
Drag & Drop Links with fragments drop the fragment

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#550]
### What went wrong?
- When dragging a link with a url fragment (like `/page/page-slug#heading`) to a map to create a marker, the new marker does not include the fragment.

### What were you expecting to happen?
- For the marker to include the fragment. 

### What steps can we follow to reproduce the issue?
1. Create a page containing with a link with a fragment like (`/page/page-slug#heading`)

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14.6

**Comment by jurex** [comment]
fixed
