### ISSUE TITLE
Links to pages containing "gif", "webp" or other image extensions tries to load an image

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#551]
### What went wrong?
- Links to pages containing "gif", "webp" or other image extensions tries to load an image instead of the page
- The text can appear anywhere in the slug

### What were you expecting to happen?
- The link to load the linked page

### What steps can we follow to reproduce the issue?
1. Create a page with a name containing an image extension, like "gifts"
2. Create a link to that page from another page. (I.e. `/page/gifts` (It seems that links that don't start with `/page` still work as expected))
3. Reload that page 
4. Tap the link

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14.6

### Any other comments?
- It seems like a case of an unanchored regex for file extension. It also isn't requiring the extension start with a `.`, it's matching on `gif` not `.gif`. If using a regex, I'd suggest something like `\.(gif|a?png|jpe?g|webp)$`

**Comment by jurex** [comment]
fixed
