### ISSUE TITLE
Search bar missing when changing from slideover to fullscreen on iPad

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#553]
### What went wrong?
-  Search and back bar missing from compendium window when in the middle of a search and window changes from slide over to full screen.

### What were you expecting to happen?
- expect window to container search and back button as normal

### What steps can we follow to reproduce the issue?
1. Open compendium window on iPad as slideover multitasking
2. Go into the monster compendium
3. Search for something (goblin)
4. Tap on entry to view the monster entry
5. Grab the slideover window and drag it to the top middle to make it full screen
6. Hit back to go back to the search screen
7. Notice only search results present with no search field or back button.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.2): 
- Operating System (iPadOS): 

### Any screenshots, videos, logs, or error messages?

![A6C5EF65-CDB5-42F6-AAE6-2B1E16699162](https://user-images.githubusercontent.com/61415452/124134299-4c726d00-da48-11eb-8595-72569b9f9fe2.jpeg)

**Comment by jurex** [comment]
Looks like some weird bug in navigation controller. I've added invalidation after each screen appearance as a workaround. Hopefully apple will fix in the upcoming ios release.
