### ISSUE TITLE
Using reset to delete a page reference on a map marker doesn't delete it

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#554]
### What went wrong?
- Using reset to delete a page reference on a map marker doesn't delete the reference. It seems to be deleted but when saving the marker and check again the marker, the reference is still there.

### What software versions are you currently using?
- EncounterPlus  4.11.2
- Operating System iPadOS 14.6

**Comment by jurex** [comment]
fixed
