### ISSUE TITLE
The "Copy & Load" Map option drops anchors from the page links/references.

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#556]
### What went wrong?
Created a page where the marker referenced an anchor on a page (e.g., "/page/my-page#my-anchor"). When I chose to "Copy & Load" the map to my campaign, all of the anchors get dropped from the page references.

### What were you expecting to happen?
The anchors to be preserved in the page references

### What steps can we follow to reproduce the issue?
1. Create a map where there are links to anchors on pages. Save the map in a module.
2. Select the map and choose "Copy and Load" to the campaign.
3. Observe the anchor portion of the page reference has been deleted

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iPadOS 14.6, macOS 11.4

**Comment by jurex** [comment]
fixed
