### ISSUE TITLE
Expose certain page attributes to WebKit for JavaScript

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#557]
### What would you like to see added to EncounterPlus?
- It would be useful to have certain page attributes exposed to WebKit for use in JavaScript. Attributes such as the page id and slug, parent id and slug, and also even the containing module or campaign’s id and slug. Currently I am manually adding these to a page with `<script>window.thisSlug="page-slug"</script>` or `<script>window.parentUUID="parent-id"</  script>`

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 14.6

**Comment by jurex** [comment]
done, exposed data are in `window.data` namespace

```html
<script>
        window.data = {"module":{"id":"AA9B0CA6-E75D-4781-8CA8-CA1DE5B88AB0","name":"Examples","slug":"examples"},"page":{"id":"2BA4481B-B606-4084-9AF6-7DC70AB88A05","slug":"example-page","parentId":"","name":"Example Page"}};
 </script>
 ```
