### ISSUE TITLE
Touch Bar Buttons

### ISSUE THREAD

**Issue by haganrobb** [encounterplus/encounterplus#566]
### What would you like to see added to EncounterPlus?
- Touch Bar Buttons for MacOS
- "Start Initiative" 
- Roll dice buttons
- add map button
- shortcut to module/page/map/etc.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): macOS 11.2.3

**Comment by Malcolm-Wolter** [comment]
Rumor has it the Touch Bar is going the way of the dodo...

**Comment by haganrobb** [comment]
You mean a cool thing in an awesome part of history people will talk about for all of eternity?? Dope! ;)

**Comment by jurex** [comment]
and it's gone... seems there is no future for the touch bar anymore. closing for now. sorry guys!
