### ISSUE TITLE
Sorting and Grouping of modules

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#567]
### What would you like to see added to EncounterPlus?
- I would like to be able to sort, filter, and group modules (similar to how the compendium works) by title, author, and type

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iPadOS 15

**Comment by DHCross** [comment]
I would love to see this.

**Comment by jurex** [comment]
custom sorting and grouping can be defined now in the system configuration files
