### ISSUE TITLE
Dragging a large asset then touching with a second finger does drag + zoom

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#57]
Added an asset to the screen, selected via group select (with players), started to drag the asset + players around, then touched with a second finger and suddenly it was both dragging the asset and zooming the screen at the same time - when dragging it should lock zoom so you can't accidentally change things (at the least needs an option for this).

**Comment by jurex** [comment]
should be fixed with recent map changes. if it appears again, please re-open
