### ISSUE TITLE
Search page contents as well as titles

### ISSUE THREAD

**Issue by ep1cman** [encounterplus/encounterplus#571]
### What would you like to see added to EncounterPlus?
It would be great to have the option to also search the body text of pages with the search function. Some times I am trying to find information that is on a page but not in the title, e.g some NPC's details at a location

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):

**Comment by joelohrum** [comment]
This is a duplicate of Issue 531.
