### ISSUE TITLE
Page Editing Without Change

### ISSUE THREAD

**Issue by Rob8x10** [encounterplus/encounterplus#575]
### What went wrong?
- When editing a page, if you press save, it doesn’t show the saved page. You need to close the page and reopen it to display the edited changes.

### What were you expecting to happen?
- When saving the page, it should update the window with the new information.

### What steps can we follow to reproduce the issue?
1. Select a page, edit the page, save the page edits and view to see no changes have been made. Step 2, close the page and reopen the page and it will show the edits.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 4.11.2

### Any screenshots, videos, logs, or error messages?
No error messages.
I think my file size is too big for posting the video.
### Any other comments?
-

**Comment by jurex** [comment]
fixed, thanks for heads up!
