### ISSUE TITLE
Alerts linger for too long and block the UI [Mac]

### ISSUE THREAD

**Issue by BeauNouvelle** [encounterplus/encounterplus#584]
### What would you like to see added to EncounterPlus?
- I'd like the alert overlays to be changed to a toast or something else non blocking as they hang around for a little too long.

I'd like to see them either changed to be less intrusive, or have the ability to be dismissed by clicking/tapping on them. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.11.2
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):  macOS 12

**Comment by jurex** [comment]
Errors and info messages are dismissible now by tap/click events. For loading (during import/export) alerts, I need to implement it differently, using background tasks... closing for now

**Comment by BeauNouvelle** [comment]
Thank you so much. A very good QOL improvement!
