### ISSUE TITLE
Crash after applying damage to removed-from-combat monster

### ISSUE THREAD

**Issue by Shidara1** [encounterplus/encounterplus#586]
### What went wrong?

Was attempting to deal damage to a monster - giant rat.  

Damage popup was opened via multiple clicks on the giant rat.

Got distracted by PC question, then right clicked on the monster token and selected "Leave Combat"

Entered 7 damage to the damage popup (which still pointed to the giant rat) and clicked "=".

Damage popup display went from 7 to zero, as it was enough to kill the monster, but the token image remained on the map, and no bloodstain image was placed. I believe the damage popup remained open, don't remember for sure.

Right-clicked and attempted to delete the giant rat token, but it remained.  Repeated the attempt to delete the token via right-click menu 3-4 more times, each time the token failed to delete.  

I then moved the token out of the area we were using and attempted to continue play. Was able to move the token successfully.

A player started moving his character via the web client, and E+ crashed to Finder. I believe the token was about 3-5 squares away from its start position when the crash occurred. Not sure if if the PC movement was related, it might have been a coincidence.

Upon relaunching after crash, PC and giant rat were in pre-movement locations, and the giant rat was successfully deleted from the combat. Player was able to move his character token normally.

### What were you expecting to happen?
- Not sure, but not a crash.. E+ probably got confused with the out-of-combat monster getting damage.  E+ should probably close the damage popup when if the current monster is removed from combat.

### What steps can we follow to reproduce the issue?
The above process might repeat the crash - attempt to deal damage to a monster that has left combat.

### What software versions are you currently using?
- EncounterPlus 4.11.2 (2366)
- macOS 11.4 (20F71)

### Any screenshots, videos, logs, or error messages?

Log attached.
[EPlus Crash Description.txt](https://github.com/encounterplus/encounterplus/files/7193575/EPlus.Crash.Description.txt)

**Comment by jurex** [comment]
fixed in multiple places. Thanks for heads-up and crashlog!!!
