### ISSUE TITLE
Remove torn paper effect from compendium artwork with alpha channel

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#588]
### What would you like to see added to EncounterPlus?
- Remove torn paper effect from compendium artwork with alpha channel
- When compendium artwork has an alpha channel, the torn paper effect at the top edge make it appear that the artwork is clipped

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.12.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 15

**Comment by jurex** [comment]
done
