### ISSUE TITLE
Last place long pressed ignores input

### ISSUE THREAD

**Issue by justinanderson** [encounterplus/encounterplus#591]
### What went wrong?
- When I long press on a map, it leaves behind a region which ignores the start of touches until I long press a different area.

### What were you expecting to happen?
- That I could still interact with the area I had just long pressed on.

### What steps can we follow to reproduce the issue?
2. Long press somewhere on a map to bring up a context menu.
3. Dismiss the menu.
4. Try to use any tool where you just long pressed.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.12.0 (2490)
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iPadOS 14.8

### Any screenshots, videos, logs, or error messages?
- I can provide one if needed, but a video of nothing happening may not be useful.

### Any other comments?
- Regions like this can still be drawn on if you start your drawing outside of the region.
- After long pressing in a second area, the first area ignores the first touch start inside of it but then recognizes subsequent ones.
- This occurs a lot if you are trying to draw small things or make small changes to assets or tokens.
- I'm seeing this is on an iPad Pro (12.9-inch) (3rd generation).
- This happens both with an Apple Pencil and with direct touches.
- I was seeing this in EncounterPlus 4.11 as well but hadn't reported it yet.

**Comment by jurex** [comment]
Long press touch (context menu) on map is implemented by context menu interaction API, which must use some view as a target preview. I workaround it by using 1x1 px transparent dummy view, but it looks like it's also consuming other touches, even if it's transparent. Disabling interaction on it seems to fixed it. 

thanks for heads up and reproducible steps!
