### ISSUE TITLE
Crashed when quitting app

### ISSUE THREAD

**Issue by Shidara1** [encounterplus/encounterplus#603]
### What went wrong?
- I quit the app, and instead of quitting normally, the app crashed.

### What were you expecting to happen?
- Normal quit to Finder.

### What steps can we follow to reproduce the issue?
1. Not sure, probably related to my compendium etc.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1):  4.12.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):  Big Sur 11.4

### Any screenshots, videos, logs, or error messages?
Crash Log attached

### Any other comments?
- After the crash, E+ started back up just fine, with no lost data (that I could see), and successfully quit to finder
[Crash log 2.txt](https://github.com/encounterplus/encounterplus/files/7274540/Crash.log.2.txt)
.

**Comment by jurex** [comment]
I think this is related to the #598. Closing for now, but please re-open if it happens again
