### ISSUE TITLE
Improved Filtering of monsters (and others)

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/encounterplus#604]
### What would you like to see added to EncounterPlus?

This is a specific example but may be more broadly applicable.  

If I filter monsters by "desert" type, I'd love the option to see monsters that ONLY have the desert tag.  

Likewise, many monsters have _all_ environments selected, I'd love an option to ignore those when filtering for desert monsters, so when i filter by desert, i remove many of the generic monsters. 

Vaguely related to other filter requests like this https://github.com/encounterplus/encounterplus/issues/228

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.12
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): Both

**Comment by jurex** [comment]
done
