### ISSUE TITLE
Add Exhausted condition

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#618]
### What would you like to see added to EncounterPlus?
- Add **Exhausted** to the default conditions list.
- Possibly enumerated as levels 1-6

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.12.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 15.1

**Comment by jurex** [comment]
Conditions, diseases and custom effects are now editable and part of the library.
