### ISSUE TITLE
Feature Request: "World Map" type of Map

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#62]
Nearly all maps will be encounter level maps, where you move individuals (whether by grouping or not) - it would be useful to have a World Map mode, where instead of showing the individual party members and mobs, instead show a party icon that can be moved around, and have the scale in miles / leagues (set in the map) rather than feet.

This would also benefit from always showing the distance travelled when dragging rather than needing to be in an encounter.

This sort of links in with #24 as world maps tend to work better with that.

Linking to #61 this could have three colours - slow travel, normal travel, fast travel - with a "Next Day" button instead of "Start Combat", to reset the amount of travel done.

**Comment by Rycochet** [comment]
The party icon might want to be a Map Marker style, rather than "filling the grid cell" - so the map can zoom in and out without losing the position of the party.

**Comment by jurex** [comment]
I did some improvements regarding this. New token settings will allow you to create some nice looking pins, and you can customise map units and scale. I will close this for now, as I feel we don't need a separate `travel` type map for now, but might revisit it later if necessary. thanks for feedback tho
