### ISSUE TITLE
E+ doesn't capture initiative rolls from dndbeyond game log via EncounterLog if encounter is running

### ISSUE THREAD

**Issue by spacebag** [encounterplus/encounterplus#626]
### What went wrong?
- Player with no initiative roll set on their character rolls initiative after encounter is started, but initiative value is not set on their character.

### What were you expecting to happen?
- Initiative rolls should be captured on the player character if they don't already have an initiative value set, regardless of encounter state, and the character should be added to the initiative order automatically if the encounter is already running.

### What steps can we follow to reproduce the issue?
1. Create a dndbeyond campaign with players in it.
2. Install Encounterlog and open dndbeyond campaign in it.
3. Player opens the character sheet for their character that belongs to the dndbeyond campaign
4. DM starts encounter in Encounter+
5. Ensure player character does not have initiative value set.
6. Player rolls initiative in dndbeyond.

Chat log will display initiative roll from player, but character's initiative value is not captured in the combat tracker if encounter is running.

### What software versions are you currently using?
- EncounterPlus: v4.12.1 (2515)
- EncounterLog: v2.2.3 
- Operating System: macOS v11.6 

### Any other comments?
- rrgeorge says this is down to "how E+ handles initiative from the API" (https://discord.com/channels/565243968858751027/872128156285427772/902238715479474256)

**Comment by jurex** [comment]
it's not exactly a bug, because it was intentional behaviour due to some internal stuff, but I agree that it should work regardless of the encounter state.  fixed! thanks!
