### ISSUE TITLE
Typo in JSON API for overlayHandoutText

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#633]
### What went wrong?
- In the json api, the key `overlayHandountText`should be `overlayHandoutText`

### What were you expecting to happen?
- 

### What steps can we follow to reproduce the issue?
1. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.13.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 15.1

### Any other comments?
-

**Comment by jurex** [comment]
fixed
