### ISSUE TITLE
WebSocket doesn't send screenUpdated when changing handout style

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#634]
### What went wrong?
- The websocket does not send a `screenUpdated` event when they handout style is changed

### What were you expecting to happen?
- 

### What steps can we follow to reproduce the issue?
1. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 

### Any other comments?
-

**Comment by jurex** [comment]
fixed
