### ISSUE TITLE
The option to only drop assets as assets

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#637]
### What would you like to see added to EncounterPlus?
- Currently if you drag and drop an asset on the token layer, it creates a token instead of an asset. I personally rarely need this feature, and would like a setting to make this optional. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.13.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.2

**Comment by Taliesin1** [comment]
This happens to me all the time. Would love a way to stop that from happening.

**Comment by raulthepoolboy** [comment]
I also run into this all the time. Potential solutions/options:

- Allow option to convert Assets to Tokens and vice versa.
- Allow setting a default option for adding new Assets: "Drag and drop Assets as Tokens" or "Drag and drop Assets as Assets" or "On drop, present dialog with choice to 'add as Asset' or 'add as Token'"

**Comment by jurex** [comment]
It's behaving like this only on the `Token` layer. If you select any other layer, app will create a tile from asset. Closing for now, as it's intended, but please re-open if you still find it annoying.

**Comment by rrgeorge** [comment]
It’s understood that this is working as intended, but this feature request is to be able to disable that behavior.

**Comment by Taliesin1** [comment]
Agreed. I very rarely (if ever), drag and drop images as tokens. I usually have those applied with the character or monster record in advance. But I do very frequently drag and drop assets and place them as tiles when I'm building out a map. I guess what I'm suggesting is that the default state for drag and dropping images _onto the map_ should be tiles going to the Object layer.
