### ISSUE TITLE
Feature Request: Lock map (so copy only)

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#64]
Needs to be a setting in the module itself - so that maps can be copied into the campaign, but the original can never be edited.

Probably wants support for #43 first, then doors could have an ID that gets saved in the campaign, allowing the map to be re-loaded without losing the "open" state of the doors.

Questions relating to assets directly on the map - should the changes also be remembered so updating the base map can be done without losing anything?

**Comment by Splinter714** [comment]
@Rycochet Is this solved by the current version's prompt when loading a map?
> copy and load?
> load?

**Comment by Rycochet** [comment]
> @Rycochet Is this solved by the current version's prompt when loading a map?
> 
> > copy and load?
> > load?

Haven't a clue as I stopped using this over a year ago - so close as you feel appropriate :-)

**Comment by Splinter714** [comment]
Done in previous update
