### ISSUE TITLE
Blank label circles appear on some tokens.

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#641]
### What went wrong?
- Some tokens display a blank circle with no label — even when there's no label in the token’s “Label” field.

### What were you expecting to happen?
- If the token has label, the circle should not appear at all..

### What steps can we follow to reproduce the issue?
Not sure. It seems intermittent and doesn't happen with all tokens, but see screenshot for example.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.13.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):  macOS 11.6

### Any screenshots, videos, logs, or error messages?
See attached.

### Any other comments?
-
<img width="594" alt="Screen Shot 2021-11-14 at 1 23 41 PM" src="https://user-images.githubusercontent.com/10515719/141695751-eba657d6-dd8c-42d6-9c9d-7fa14ad7bff5.png">

**Comment by jurex** [comment]
hmm, can't replicate it at all.

**Comment by rrgeorge** [comment]
1. Delete the token
2. Edit the entry in the combat tracker and remove the label
3. Create the token

**Comment by jurex** [comment]
lol I should read comments first before working on issues :) took me a while to discover the root cause by myself, thanks @rrgeorge anyway..

fixed
