### ISSUE TITLE
Selecting multiple tokens and dragging only moves one token

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#643]
### What went wrong?
- When selecting multiple tokens, and trying to move the group, only one moves

### What were you expecting to happen?
- all selected tokens should move when multiples are selected, ideally with the group movement setting. 

### What steps can we follow to reproduce the issue?
1. Put several tokens on the map
2. Use the select tool to select them all
3. Drag one of them. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.13.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): ios 15.2

### Any other comments?
-

**Comment by jurex** [comment]
fixed
