### ISSUE TITLE
Area Effects not hiding correctly in E+

### ISSUE THREAD

**Issue by Shidara1** [encounterplus/encounterplus#645]
### What went wrong?
- Area effects drawn in the E+ app do not correctly show hidden/unhidden status when switching between DM and Player views. If Hidden in DM view, the area effect remains visible when switching to Player view.  If hidden while in player view, the area effect remains hidden when switching to DM view.

### What were you expecting to happen?
- The Area Effect should accurately represent its hidden or unhidden status in both views.

### What steps can we follow to reproduce the issue?
1. In DM view, create an area effect.
2. Right-click on it and choose to hide the area effect. The area effect gets a dotted line border.
3. Switch to PC view. The area effect does not disappear, but retains the dotted line border.
4. Right click to unhide, and the area effect border goes from dotted to solid.
5. Right-click and hide the effect.  The effect disappears completely.
5. Switch to DM view. The area effect does not reappear. The effect can still be right-clicked on as normal.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.13.1 (2548)
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 11.4 (20F71)

### Any screenshots, videos, logs, or error messages?

Nope.

### Any other comments?
- The Web Client view is unaffected by this bug.  In the web client, the effect disappears and reappears accurately regardless of the DM's view in E+. It appears to be only in the main E+ app.

**Comment by jurex** [comment]
fixed, thanks for report!
