### ISSUE TITLE
Diacritic marks in first letter doesn’t show and doesn’t automatically assign tokens with same name

### ISSUE THREAD

**Issue by FrostyMisa** [encounterplus/encounterplus#647]
### What went wrong?
-When my monster name is Šakal and his token is Šakal as well (already set asset pak for tokens in settings), when I insert monster to battle map it doesn't automatically assign corresponding token. Others without diacritics works well. Jestřáb doesn't work. 
And for Šakal monster, in compendium, when I open his description and first letter is with diacritics, it doesn't show it here, but search function works ok for monsters, but no for tokens with diacritic. 

### What were you expecting to happen?
-it will automatically assign monsters with tokens contains diacritics. 

### What steps can we follow to reproduce the issue?
1. Make monster Šakal or Ježibaba and in your token folder make token with same name, after in library try to search "Šakal", it will find monster, but not his token. When you insert him to map, he will be without token. Token search works when you skip diacritic letter, like you search for "kal", it will find Šakal in monsters and in tokens. 

### What software versions are you currently using?
- EncounterPlus: 4.13.1 
- Operating System: iOS 15.1.1 

### Any screenshots, videos, logs, or error messages?
https://user-images.githubusercontent.com/59890223/145710422-c72799fa-0ea5-410b-91ee-fe889f84d155.MOV

### Any other comments?
-

**Comment by jurex** [comment]
So looks like there were a couple of issues:
- Search using diacritics was not working at all (as you pointed out in the video). Got it fixed now, every search field is **case and diacritic insensitive**
- I couldn't replicate your issue with automatic asset lining from asset pack (either with Jestřáb or Šakal) but I noticed that when you copy&paste text into the monster name field, spaces or other white characters are carried over but not displayed - which is confusing and will prevent correct linking. I've added **whitespace trimming for all name fields** in the app, which should solve the issue.

anyway, thanks for the bug report
dik za info (🇸🇰)

**Comment by FrostyMisa** [comment]
I tried rename both Šakal monster and Šakal token manually in app and after search with diacritics works for both. And inserting token works as well.
For token, I write their Czech name manually in app, but for tokens I copy paste their names in windows, so maybe it will be problem you talking about. 
Thanks for your quick fix and your hard work!
Šťastný nový rok🥳🇨🇿
