### ISSUE TITLE
Bring Campaign Menu Bar Item back on iPadOS

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#648]
### What would you like to see added to EncounterPlus?
- Please bring put the campaign button back on the main menu bar on iPadOS

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.13.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.2

**Comment by jurex** [comment]
done, using new navigation bar button item groups

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/925257/222693404-aec70f09-9c9a-486b-9926-59168220bc39.png">
