### ISSUE TITLE
Accessibility Zoom feature appearing on external screen. 

### ISSUE THREAD

**Issue by cmcoursey** [encounterplus/encounterplus#653]
### What went wrong?
- When using the Zoom feature to read text in Pages, it is also doing a zoom on the external screen and showing content not meant for players. 

### What were you expecting to happen?
- The zoom feature to not affect the external screen. 

### What steps can we follow to reproduce the issue?
1. Doing the three finger tap to turn on Zoom and the external screen zooms. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 

### Any screenshots, videos, logs, or error messages?
https://cdn.discordapp.com/attachments/565243968858751029/925424397559402547/Screen_Recording_2021-12-28_at_11.17.13_AM.mov

### Any other comments?
-

**Comment by jurex** [comment]
Hmm, I can't replicate this issue on ipadOS 15.2 using macOS 12.1 as airplay target. will try with appletv..

**Comment by jurex** [comment]
tried on ipadOS 15.2 and apple tv 15.1, still no luck... it could be fixed by apple in iOS 15 sdk used in the latest E+ version (not public yet).. closing for now, but please re-open if the issue surface again. Thanks!
