### ISSUE TITLE
Viewport outline incorrect in portrait

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#656]
### What went wrong?
- The displayed viewport box is incorrect if airplay is set to portrait

### What were you expecting to happen?
- for the viewport to also be portrait

### What steps can we follow to reproduce the issue?
1. Set the viewport to Visible
2. Turn on AirPlay Portrait Mode
3. Connect airplay
4. Present map

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.13.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 15.3

### Any other comments?
-

**Comment by jurex** [comment]
fixed
