### ISSUE TITLE
Circle token type defaulting on token packs when I have “top down” set as my default

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#657]
### What went wrong?
I have my default token type in the options set to "top down" but when loading tokens from a token pack they always default round.  

### What were you expecting to happen?
- I expect my default in the settings to be honored

### What steps can we follow to reproduce the issue?
1. Set default token type to top down. 
2. Assign token pack
3. Load in a token that pulls a token from the pack
4. Note that it has circle as its token type.  

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System iOS: 15.1

### Any other comments?
-

**Comment by jurex** [comment]
fixed
