### ISSUE TITLE
Overide Initiative modifier for monsters and NPCs

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#663]
I'd love the ability to override the Initiative modifier on monsters and NPCs. This is because sometimes the critter can have a special ability, feat, or magic item that could... modify... the... erm... modifier. It should still pull the Dex bonus as default, but I'd like to be able to simply write over it.
- 

### What software versions are you currently using?
- EncounterPlus 4.14
- Operating System: All OSs

**Comment by jurex** [comment]
done
