### ISSUE TITLE
Gamepad - Joystick Movement too Fast on Smaller Maps

### ISSUE THREAD

**Issue by DanDM84** [encounterplus/encounterplus#664]
### What went wrong?
- On smaller-sized maps, the joystick movement when using a gamepad moves very quickly, making it difficult to move the token to the right location. Players end up using the less-flexible d-pad.

### What were you expecting to happen?
- Movement speed of the token using the joystick should be similar across maps of all sizes, and reasonably slow so that users can move their tokens with more precision

### What steps can we follow to reproduce the issue?
1. Using a map sized 3240x2640, the token movement was far too fast
2. Using a map size 7500x7500, the token movement was just about right

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iPadOS 15.1

### Any screenshots, videos, logs, or error messages?
Placed in beta-testing channel on Thursday, Jan 20, 2022 - around 3:24 MST

### Any other comments?
-

**Comment by jurex** [comment]
fixed. token movement using gamepad is now scaled based on the grid size
