### ISSUE TITLE
Pencil/Highlighter Flyout Menus

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#67]
When the pencil or highlighter flyout menus are open and you press a color, the flyout closes -- but not when you choose a new shape or thickness. The flyout should stay open so that you can chose a color, shape, and thickness in one go, and then close once you've pressed anywhere on the map. This is the way the spell effects flyout currently operates.

**Comment by jurex** [comment]
fixed, thanks @dmmagic
