### ISSUE TITLE
Webclient should redirect client to client/

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#670]
### What went wrong?
- When loading the webclient in a browser without the trailing slash, it gives a “Not Found” message. 

### What were you expecting to happen?
- It should return a 301 response, directing the client’s browser to the correct `/client/` url

### What steps can we follow to reproduce the issue?
1. Turn on the webclient
2. Load `http://<your ip>:8080/client` In a browser

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.3

### Any other comments?
-

**Comment by jurex** [comment]
done
