### ISSUE TITLE
Better Error Message when no webclient is installed

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#671]
### What went wrong?
- When trying to load the webclient without installing it, the clients browser will receive the following message
`IOError (not found)
open(file:oFlag:mode:): No such file or directory (errno: 2) `

### What were you expecting to happen?
- A less cryptic message indicating the web client is not installed. Maybe:
- “No web client installed. The latest version can be installed through settings.”

### What steps can we follow to reproduce the issue?
1. Delete the current installed version of the webclient 
2. Load `http://<your ip>:8080/client/` in a browser

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.3

### Any other comments?
-

**Comment by jurex** [comment]
done
