### ISSUE TITLE
Tables : display of non reference words in messages window

### ISSUE THREAD

**Issue by Tixuoty66** [encounterplus/encounterplus#673]
### What would you like to see added to EncounterPlus?
Be able to display the text AND the result of a roll in messages window. Ex « Double damage, and if this attack deals psychic damage, you develop a form of short term madness : {#table madness} ». At the moment, only the result of the roll in the madness table is displayed, without the text before.

### What software versions are you currently using?
- EncounterPlus 4.14.1

**Comment by jurex** [comment]
done
