### ISSUE TITLE
More menu (…) does not work on messages on iphone

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#674]
### What went wrong?
- The more (…) menu does not work on the messages window on iPhone or iPad in split screen 50% or less. 

### What were you expecting to happen?
- For the menu to open when pressed on

### What steps can we follow to reproduce the issue?
1. Open the app on an iPhone or in split screen on iPad 
2. Open the messages pane
3. Press the more (…) menu
4. Nothing happens

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.3

### Any other comments?
-

**Comment by jurex** [comment]
fixed
