### ISSUE TITLE
Add a "Footnotes" field to Tables

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#675]
I'd love to see a "Footnotes" field added to tables. This could offer additional notes based on some of the table entries, or just general commentary on the table, if needed. It could live under "Description" on the main table Edit screen. It should appear below the table, but before the "Source"  and "Link" info, which should be at the very bottom of the Table screen.
- 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): All

**Comment by jurex** [comment]
done
