### ISSUE TITLE
Support the new Monster Stat Block Format

### ISSUE THREAD

**Issue by jacobjohnston** [encounterplus/encounterplus#676]
### What would you like to see added to EncounterPlus?
I'd like to see support for the new Monster Stat Block format in E+. None of the changes should be incompatible with the old stat block data, but rather, a superset of the existing data.

- A "Bonus Actions" set that comes after Actions and before Reactions. Bonus Actions have the same display format as Actions and Reactions.
- A "Mythic Actions" set that comes after Legendary Actions. Bonus Actions have the same display format as Legendary Actions.
- Legendary and Mythic Action titles are bolded, but not italicized.
- Many Alignments now have "Typically" in front of them: I suggest making it a freeform text entry rather than a selection.
- Spell names are italicized when they appear in the stat block. This includes when they are displayed in the AC portion, for example "AC: 12 (15 with _mage armor_)" 

### What software versions are you currently using?
- EncounterPlus: 4.14.1
- Operating System: All

**Comment by jacobjohnston** [comment]
Per discussion, official sources leave Lair Actions and Regional Effects in the description.

**Comment by jurex** [comment]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/925257/152424960-674e2b00-74e6-41c3-a9c3-0347ce28e162.png">

new xml elements `<bonus></bonus>` `<mythic></mythic>`

**Comment by Taliesin1** [comment]
Those subheads (Actions, Bonus Actions, etc.) could really benefit from about 4 px more space above them.

**Comment by jurex** [comment]
> Those subheads (Actions, Bonus Actions, etc.) could really benefit from about 4 px more space above them.

I will work on better visual in the next release

**Comment by Taliesin1** [comment]
When you get to that part, I’d be happy to help. My degree is in graphic communications and I’ve been a front-end designer for over 20 years. I teach regular seminars on typography to designers in the branding firm in which I’m a partner. Very experienced in type design.
