### ISSUE TITLE
Some table rolls display incomplete in messages 

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#677]
### What went wrong?
- The following message does not display properly in the messages window in E+
```json
{
"id": "A7F0CDD4-6792-4477-9CBC-B9A6201F6E4D",
"created": "2022-01-28T20:53:14Z",
"content": "{\"formula\":\"1d10\",\"id\":\"74754795-FD9A-40B4-BDE9-42B5F7935E95\",\"result\":4,\"details\":[{\"name\":\"Denizens\",\"value\":\"1 patriar (human [noble](\\/monster\\/373ac358-be05-56ec-902c-d2e4ee54144c)) and 6 personal bodyguards ([veterans](\\/monster\\/84a20eb9-b680-5769-9296-a919ae53e64d))\"}],\"name\":\"Table B: Upper City Denizens\",\"reference\":\"\\/table\\/62fd4cb9-b8f3-426c-a177-0926ee1ff4db\"}",
"type": "tableRoll"
}
```
![A9BC0948-5546-4937-A1E9-4A5993DE95F6](https://user-images.githubusercontent.com/8526392/152554181-62bf6eb5-92cd-4b5a-bf00-27a2298bb2c5.jpeg)

### What were you expecting to happen?
- It should appear like this:
![6DE0D3F9-5B9E-4683-8A94-6906F75706B0](https://user-images.githubusercontent.com/8526392/152554267-d36a343d-f580-46f3-84aa-6fc5b23bcf2a.jpeg)

### What steps can we follow to reproduce the issue?
1. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.3

### Any other comments?
-

**Comment by jurex** [comment]
fixed, the issue was with the wrong cell height calculation
