### ISSUE TITLE
Allow other categories for modules, "rule" in particular

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#679]
### What would you like to see added to EncounterPlus?
- Currently modules can only be categorized as "adventure" or "other", and defaults to "adventure". It the module.xml contains any other string for `<category>`, it is ignored and set to "adventure".
- I would like to at least be able to use the "rule" category.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.3

**Comment by jurex** [comment]
changed into free form text
