### ISSUE TITLE
URL Hash fragments appear to be stripped when opening links from table results and messages

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#681]
### What went wrong?
- If a table roll result contains a link to a url with a hash fragment, the fragment appears to be stripped from the url when opening the link from table results or messages.

### What were you expecting to happen?
- The fragment to be preseved

### What steps can we follow to reproduce the issue?
1. Create a table with a link in the results containing a url fragment (e.g. `/module/abc/page/somepage#heading2`)
2. Roll the table
3. Click on the link

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.14.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.3

### Any other comments?
-

**Comment by jurex** [comment]
fixed
