### ISSUE TITLE
API fields missing

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#690]
### What went wrong?
- 4.15 is missing some API fields:
- `game.paused`
- And for monsters:
  - `game.creatures[].name`
  - `game.creatures[].hitpoints`
  - `game.creatures[].health`

### What were you expecting to happen?
- 

### What steps can we follow to reproduce the issue?
1. 

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.15.0
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 15.4

### Any other comments?
-

**Comment by jurex** [comment]
`name`, `hitpoints`, `health` fields are visible for every creature type now, and `paused` field has been moved from `game` to the API top-level hierarchy, supported with a new `systemPaused` api event.
