### ISSUE TITLE
Minimalist Initiative List Option on DM View

### ISSUE THREAD

**Issue by DanDM84** [encounterplus/encounterplus#699]
### What would you like to see added to EncounterPlus?
- There are a few of us that would like to see a more minimalist view of the initiative order for the DM view. 
- The current initiative list takes up substantial screen real estate
- Perhaps provide options on sizing (include health or not, etc).

Recommended changes include:
https://discord.com/channels/565243968858751027/634387773872275466/943617238081101904
![image](https://user-images.githubusercontent.com/51212235/156228638-61a0170e-6c19-4913-8613-b38ba0f845be.png)

https://discord.com/channels/565243968858751027/582622828201902093/948276845076435005
![image](https://user-images.githubusercontent.com/51212235/156228738-e4247f5b-4374-43d0-8549-6a5b0a691977.png)

This feature request has been upvoted/requested by DanDM, KelYCo, Team-Hufflepuff and MrWickedClown

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):

**Comment by jurex** [comment]
done
