### ISSUE TITLE
Add overscan options to external screen configuration

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#7]

**Comment by schemen** [comment]
Yes please \o/

**Comment by jurex** [comment]
still need proper testing

**Comment by jurex** [comment]
Hmm, cannot test this properly, my TV/Monitor is working fine, without black bars using direct cable, no matter the settings. I'm going to release it, so maybe you will have more luck @schemen

**Comment by schemen** [comment]
Will do, i'll give you feedback as soon as it's released.
