### ISSUE TITLE
Source Field Missing from UI

### ISSUE THREAD

**Issue by thecrazyspy** [encounterplus/encounterplus#700]
### What went wrong?
- There's a "source" tag in an exported item or spell compendium XML file. However, there's no "source" field available on the UI when creating/editing an item in your compendium through the app.
- If you include the source tag in an imported item XML, it's not displayed anywhere.
- If you export an item you previously imported with a source tag value, that value is maintained if you export the item again.

### What were you expecting to happen?
- Source field available when editing an item or spell.
- When viewed, the source is displayed on an item or spell (perhaps under the weight or duration field, before description?).

### What steps can we follow to reproduce the issue?
1. In the EncounterPlus app, open your library (click the book icon in the upper right corner).
2. Under the compendium section, select the "Items" option.
3. Select the plus symbol (+) in the upper right corner of the left-hand navigation pane.
4. Create an item: Enter item name (Lorem ipsum dolor), select an item type (Light Armor), choose rarity (common), enter attunement (left blank), enter a value (1.00 gp), enter an AC (11), enter a weight (11), then enter a description (Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...).
5. Click the "Save" option in the upper right of the edit dialog box.
6. Select the newly created item from your items list
7. In the upper right corner of the window, click on the ellipses (...), then select the export option.
8. Enter a "Save As" name, choose the location you will save your file to, then click the "Save" button in the bottom right corner of the save dialog box.
9. Unzip the exported file.
10. Open the compendium.xml file in some editing program (I use vscode) to view the source field.
11. Enter a new source name (sunt in culpa qui officia), and save the XML file.
12. Open the EncounterPlus app, then select the gear icon in the upper left corner of the window. 
13. Choose the import option.
14. Find and select the compendium.xml file you modified, then click the "Open" button.
15. Close the "Setting" dialog box, then open your library (tap the book icon in the upper right corner).
16. Under the compendium section, select the "Items" option.
17. Find and select your item (Lorem ipsum dolor) and review the information in the right-hand pane. Note there is no "source" field.
18. In the upper right corner of the window, tap on the ellipses (...), then select the "Edit" option.
19. Note there is no source field.
20. If you can export the item again (steps 7-10) and review the compendium.xml file, you'll see the source you entered in step 11 is still present.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.15.0 (2766)
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): macOS 12.2.1

### Any screenshots, videos, logs, or error messages?

Create item:
<img width="430" alt="Create item example" src="https://user-images.githubusercontent.com/77707573/156631187-1cc4e231-29fc-4de2-932a-b112c4276a54.png">

View created item:
<img width="756" alt="View item after creation example" src="https://user-images.githubusercontent.com/77707573/156631213-267283b7-cb86-4f30-8701-a3d7c4eaf705.png">

Original XML export:
<img width="1001" alt="original compendium xml example" src="https://user-images.githubusercontent.com/77707573/156631284-3d60a2b9-5769-4671-a962-6758c56d3916.png">

Updated XML to import:
<img width="1000" alt="updated compendium xml example" src="https://user-images.githubusercontent.com/77707573/156631265-1c817a12-5e83-4c36-9ac1-37a25458a88b.png">

Source still missing:
<img width="759" alt="Source still missing item example" src="https://user-images.githubusercontent.com/77707573/156631309-d6b6c75e-23fa-4d8b-8ee2-332333c70b1d.png">

### Any other comments?
- This may be a feature request rather than a bug. The tag is present in the XML file but not in the app itself. The missing field may be a leftover option from a previous version or a future version? 
- It's fantastic that there's a source tag, and it'd be great to be able to use it!
- The steps provided are for an "item", but the same issue exists on "spell". It would be great to have this option on monsters.

**Comment by jurex** [comment]
`source`, `page`, `link` fields will be present on every entity type in future release. stay tuned!

**Comment by jurex** [comment]
fixed
