### ISSUE TITLE
Cannot enter negative initiative on iphone

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#714]
### What went wrong?
- You cannot enter negative initiative on iPhone, because apple does not give a `-` key on the numeric keyboard on iPhone.
- Currently the only way to get a negative number is to copy and paste a `-` from another field.

### What were you expecting to happen?
- Some characters may have a negative initiative bonus, so there should be a `-` or `+/-` button available with the numeric keyboard. 

### What steps can we follow to reproduce the issue?
1. Edit a player
2. Try to input a negative initiative value

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.15.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 15.6

### Any screenshots, videos, logs, or error messages?
![4F9B7038-425A-45A4-8B54-36FAD42D4A34](https://user-images.githubusercontent.com/8526392/170885910-30dd5936-64f1-4902-94f1-e4d2e2d75445.png)

### Any other comments?
- If possible, maybe this floating number pad can be used for all numeric input fields?
![DE0318A3-E4B2-45C2-8D92-1E3C1D129BB7](https://user-images.githubusercontent.com/8526392/170886134-2892328c-58cf-46ef-8da5-6a7ad4e12e7f.jpeg)

**Comment by jurex** [comment]
Changed the keyboard type to [numbersAndPunctuation](https://developer.apple.com/documentation/uikit/uikeyboardtype/numbersandpunctuation). Will probably make it default for all Integer based fields in the new swift UI forms.
