### ISSUE TITLE
Map images with the same filename but different path are cached as a single image

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#722]
### What went wrong?
- Maps backgrounds are cached based on file name not full path. Similar to #510 
- If multiple maps use the same base file name (eg `market/rooftop.jpg` and `castle/rooftop.jpg`), the will show the same image for the background (whichever was loaded first)

### What were you expecting to happen?
- The correct background image should be displayed.

### What steps can we follow to reproduce the issue?
1. Create a module with maps using 2 different images with the same name but different paths — eg `market/rooftop.jpg` and `castle/rooftop.jpg`
2. Load the module
3. Load one map
4. Load the other map
5. Load the first map again

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.15.3
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): iOS 16

### Any screenshots, videos, logs, or error messages?
See discussion on discord starting here: https://discord.com/channels/565243968858751027/978780768572694540/988973486422757428

### Any other comments?
- Probably the same issue as #510

**Comment by jurex** [comment]
fixed by using ```UIImage(contentsOfFile: path)``` instead of ```UIImage(named: path)``` 
will add a custom image caching later in the subsequent release
