### ISSUE TITLE
Sort monsters by role

### ISSUE THREAD

**Issue by DHCross** [encounterplus/encounterplus#724]
### What would you like to see added to EncounterPlus?
- 
I would like to "sort by role" for monsters to find all creatures with the "npc" role quickly. Or maybe two criteria "role and type" and so on. 

### What software versions are you currently using?

4.15.3 (2808)
IOS 15.6

- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3")

![image](https://user-images.githubusercontent.com/45954119/175389040-1cc05f0f-e208-4c14-9dc7-03ebfcfb88c5.jpeg)

**Comment by jurex** [comment]
Role field in monster statblock will be deprecated in 5.0.0, you can use NPCs section for npcs, sidekicks and other friendly creatures
