### ISSUE TITLE
New Compendium Entities — NPCs, Sidekicks, and Vehicles

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#730]
### What would you like to see added to EncounterPlus?
Right now, monsters and NPCs share an entitiy type — namely, "Monster". I'd love to able to have an NPC entity (using the current monster stat block, I guess) as well as a "Sidekick" type that would use the Sidekick stat block variant. These tokens should also be able to move with the party in Snake movement mode, and be placed with the party, maybe.

Lastly, a "Vehicle" type for things like Wagons, and siege machines, like Trebuchet and Ballistas. Although, it may be nice to have a separate "Siege Machines" entity, that would be very similar to "Vehicles" but could be filtered in search as a Siege Machine.

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 4.15.4
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):  macOS 12.3.1

**Comment by Taliesin1** [comment]
What should these stat blocks look like? Well I'm glad you asked! Here's one for a Siege Machine. Note it would not need an alignment attribute.
<img width="461" alt="Screen Shot 2022-07-14 at 8 05 59 AM" src="https://user-images.githubusercontent.com/10515719/178990228-decac9a4-9a2d-41f2-bcd6-dbf316f4731d.png">
!

**Comment by Taliesin1** [comment]
Here's a vehicle (Ship)
![Screen Shot 2022-07-14 at 8 07 48 AM](https://user-images.githubusercontent.com/10515719/178990449-b8cd055f-31e4-4c53-9fef-c1f3ec4881ee.png)
:

**Comment by jurex** [comment]
got this covered with the new vehicle stat block

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/925257/208641531-d02dc86b-fe6c-487c-9033-79254fac70d2.png">
