### ISSUE TITLE
Reorder content "chunks" in Compendium item, monster, and table entries

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#753]
### What would you like to see added to EncounterPlus?
I'd love to be able to resequence or reorder content "chunks" in a compendium entry by simply dragging and dropping them in the interface. So — Traits, Actions, table rows, etc., etc. 

### What software versions are you currently using?
- EncounterPlus: 4.15.4
- Operating System : iOS and MacOS

**Comment by jurex** [comment]
done
