### ISSUE TITLE
Map Preview Doesn't Update

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#77]
When I save changes I've made to a map, the map "preview" doesn't update. For example, I'm working with the Example Map in the Examples module. The way it ships with E+, it has two pins and several squiggles made with the pencil and highlighter tools. If I were to delete the pins and add a bunch of other stuff, like some spell effects, and then save, the preview shows none of the changes I've made.

**Comment by jurex** [comment]
It was like this in previous version, but the performance overhead for taking snapshot was not worth the benefit. So I've decided to include only map background.
