### ISSUE TITLE
Online web server for iPad

### ISSUE THREAD

**Issue by profalxandrepare** [encounterplus/encounterplus#779]
### What would you like to see added to EncounterPlus?
- the web server should be included on the iPad and mac version. With that it soule be perfect. Push an update please

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"):

**Comment by Tixuoty66** [comment]
I’m not sure to understand what you mean ? The web server is already available from iPad and from Mac.

**Comment by profalxandrepare** [comment]
I am trying to find the option « web server » on thé second screen menu. I don’t see it.

**Comment by profalxandrepare** [comment]
Great product
