### ISSUE TITLE
Saving Map Changes Needs Confirmation

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#79]
If I load a map, run a combat where a bunch of stuff was changed (creature positions, added notes with the pencil, etc) and then close the map (the little X in the upper-right-hand-corner), all those changes get saved automatically. The app should ask me first if I want to save my changes, either onto the map itself or as a copy.

**Comment by jurex** [comment]
It was like this in previous version, and it was very annoying. It's also easier for implementation. I'll work on better undo instead.
