### ISSUE TITLE
Add NPCs to List Of Things You Can Add To Campaigns And Modules

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#88]
In addition to adding Groups, Pages, Encounters, and Maps, allow NPC statblocks to be added. 

Use Case: In Ghosts of Saltmarsh, there are a number of important NPCs that are referenced throughout the campaign. You could add a Group called "Important NPCs," and in that group, have each NPC listed. Pressing on each would immediately bring up the NPC statblock.

**Comment by ep1cman** [comment]
I would extend this to allow modules to include any of the "compendium" entries (Monsters/NPCs, Items, Spells).

**Comment by jurex** [comment]
done
