### ISSUE TITLE
Unify Utility of Monster and Player Statblocks

### ISSUE THREAD

**Issue by dmmagic** [encounterplus/encounterplus#89]
As it stands right now, Monster and Player statblocks are pretty different. For example, for Players, there's no place to add attacks (helpful when they're dominated or missing for a session) or saves (good for DMs to know). For Monsters, there's no place to add Traits, Ideals, Bonds, or Flaws (good for NPCs). Full statblock support for all possible options should be available for both Monsters and Players.

**Comment by jurex** [comment]
Player statblocks will be replaced with a new character sheet. See #92
