### ISSUE TITLE
Map rendering issues using small grid size

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#9]
Things get a little problematic with a smaller grid size.
![image](https://user-images.githubusercontent.com/925257/74028197-11cae900-49aa-11ea-9462-ecefba17cead.png)

**Comment by Splinter714** [comment]
From Discord:
> Splinter: Can others confirm that this is resolved? Looks fine to me in 4.11.1
> Tixu: looks fine for me too
