### ISSUE TITLE
Encounter option to convert to corpse asset

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#94]
After an encounter is stopped, give an option in the `...` menu that converts *dead* monsters into a corpse. Show the same icon as a dead monster, just as an image asset, and remove the monster from the initiative tracker. Any monsters that are still alive should be left alone. Assets should be locked regarding size and position by default.

Optionally include characters, companions and allies in this conversion (maybe if no monsters are dead, then change the text and choice, or maybe have a submenu etc).

Optionally have the dead asset link back to the source monster / player entry for quick reference.

**Comment by Rycochet** [comment]
Also option - drop specific image asset instead of copy of monster image

**Comment by jurex** [comment]
done, with the new token workflow.
