### ISSUE TITLE
The app does not recreate the icloud folder after it was deleted

### ISSUE THREAD

**Issue by AshDevFr** [encounterplus/encounterplus#97]
A while back I removed the whole folder from my icloud drive because backup and restore were failing. At the time I thought it would reset the folder and fix my backup issues.

Since then I cannot either backup or restore because the app does not recreate the folder. 
I keep getting the message `The file “compendium.xml” doesn’t exist.`.
I know that as an alternative, I can do manual backups but it’s easier to sync via icloud.

This is happening in both the MacOS app and on iOS13 (iphone & ipad)

![image](https://user-images.githubusercontent.com/7372540/78284757-b8c49080-74d4-11ea-842f-cde43f4169e8.png)

**Comment by jurex** [comment]
Damn, the fix was easy, I should do it looong time ago...
